// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.protoqueue.sample.proto.nano;

@SuppressWarnings("hiding")
public interface TestProtos {

  // enum PacketType
  public static final int kRequestUri = 0;
  public static final int kResponseUri = 1;

  // enum ResultType
  public static final int kResultTypeOk = 0;
  public static final int kResultTypeError = 1;

  public static final class DslProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DslProto[] _emptyArray;
    public static DslProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DslProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .test.PacketType uri = 1;
    public int uri;

    // optional .test.PHeader header = 2;
    public net.protoqueue.sample.proto.nano.TestProtos.PHeader header;

    // optional .test.PRequest request = 3;
    public net.protoqueue.sample.proto.nano.TestProtos.PRequest request;

    // optional .test.PResponse response = 4;
    public net.protoqueue.sample.proto.nano.TestProtos.PResponse response;

    public DslProto() {
      clear();
    }

    public DslProto clear() {
      uri = net.protoqueue.sample.proto.nano.TestProtos.kRequestUri;
      header = null;
      request = null;
      response = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uri != net.protoqueue.sample.proto.nano.TestProtos.kRequestUri) {
        output.writeInt32(1, this.uri);
      }
      if (this.header != null) {
        output.writeMessage(2, this.header);
      }
      if (this.request != null) {
        output.writeMessage(3, this.request);
      }
      if (this.response != null) {
        output.writeMessage(4, this.response);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uri != net.protoqueue.sample.proto.nano.TestProtos.kRequestUri) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.uri);
      }
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.header);
      }
      if (this.request != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.request);
      }
      if (this.response != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.response);
      }
      return size;
    }

    @Override
    public DslProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case net.protoqueue.sample.proto.nano.TestProtos.kRequestUri:
              case net.protoqueue.sample.proto.nano.TestProtos.kResponseUri:
                this.uri = value;
                break;
            }
            break;
          }
          case 18: {
            if (this.header == null) {
              this.header = new net.protoqueue.sample.proto.nano.TestProtos.PHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 26: {
            if (this.request == null) {
              this.request = new net.protoqueue.sample.proto.nano.TestProtos.PRequest();
            }
            input.readMessage(this.request);
            break;
          }
          case 34: {
            if (this.response == null) {
              this.response = new net.protoqueue.sample.proto.nano.TestProtos.PResponse();
            }
            input.readMessage(this.response);
            break;
          }
        }
      }
    }

    public static DslProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DslProto(), data);
    }

    public static DslProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DslProto().mergeFrom(input);
    }
  }

  public static final class PHeader extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PHeader[] _emptyArray;
    public static PHeader[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PHeader[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    // optional uint64 seqid = 2;
    public long seqid;

    // optional .test.Result result = 4;
    public net.protoqueue.sample.proto.nano.TestProtos.Result result;

    public PHeader() {
      clear();
    }

    public PHeader clear() {
      uid = 0L;
      seqid = 0L;
      result = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      if (this.seqid != 0L) {
        output.writeUInt64(2, this.seqid);
      }
      if (this.result != null) {
        output.writeMessage(4, this.result);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      if (this.seqid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.seqid);
      }
      if (this.result != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.result);
      }
      return size;
    }

    @Override
    public PHeader mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
          case 16: {
            this.seqid = input.readUInt64();
            break;
          }
          case 34: {
            if (this.result == null) {
              this.result = new net.protoqueue.sample.proto.nano.TestProtos.Result();
            }
            input.readMessage(this.result);
            break;
          }
        }
      }
    }

    public static PHeader parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PHeader(), data);
    }

    public static PHeader parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PHeader().mergeFrom(input);
    }
  }

  public static final class Result extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Result[] _emptyArray;
    public static Result[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Result[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .test.ResultType code = 1;
    public int code;

    // optional string res_msg = 2;
    public java.lang.String resMsg;

    public Result() {
      clear();
    }

    public Result clear() {
      code = net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk;
      resMsg = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.code != net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk) {
        output.writeInt32(1, this.code);
      }
      if (!this.resMsg.equals("")) {
        output.writeString(2, this.resMsg);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.code != net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.code);
      }
      if (!this.resMsg.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.resMsg);
      }
      return size;
    }

    @Override
    public Result mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk:
              case net.protoqueue.sample.proto.nano.TestProtos.kResultTypeError:
                this.code = value;
                break;
            }
            break;
          }
          case 18: {
            this.resMsg = input.readString();
            break;
          }
        }
      }
    }

    public static Result parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Result(), data);
    }

    public static Result parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Result().mergeFrom(input);
    }
  }

  public static final class PRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRequest[] _emptyArray;
    public static PRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    public PRequest() {
      clear();
    }

    public PRequest clear() {
      uid = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      return size;
    }

    @Override
    public PRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
        }
      }
    }

    public static PRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRequest(), data);
    }

    public static PRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRequest().mergeFrom(input);
    }
  }

  public static final class PResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PResponse[] _emptyArray;
    public static PResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    // optional string name = 2;
    public java.lang.String name;

    public PResponse() {
      clear();
    }

    public PResponse clear() {
      uid = 0L;
      name = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      return size;
    }

    @Override
    public PResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
        }
      }
    }

    public static PResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PResponse(), data);
    }

    public static PResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PResponse().mergeFrom(input);
    }
  }
}
