// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.protoqueue.sample.proto.nano;

@SuppressWarnings("hiding")
public interface TestProtos {

  // enum PacketType
  public static final int kUserRequestUri = 0;
  public static final int kUserResponseUri = 1;
  public static final int kLevelRequestUri = 2;
  public static final int kLevelResponseUri = 3;
  public static final int kGlobalBroadcast = 4;

  // enum ResultType
  public static final int kResultTypeOk = 0;
  public static final int kResultTypeError = 1;

  public static final class DslProto extends
      com.google.protobuf.nano.MessageNano {

    private static volatile DslProto[] _emptyArray;
    public static DslProto[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new DslProto[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .test.PacketType uri = 1;
    public int uri;

    // optional .test.PHeader header = 2;
    public net.protoqueue.sample.proto.nano.TestProtos.PHeader header;

    // optional .test.PUserRequest user_request = 3;
    public net.protoqueue.sample.proto.nano.TestProtos.PUserRequest userRequest;

    // optional .test.PUserResponse user_response = 4;
    public net.protoqueue.sample.proto.nano.TestProtos.PUserResponse userResponse;

    // optional .test.PLevelRequest level_request = 5;
    public net.protoqueue.sample.proto.nano.TestProtos.PLevelRequest levelRequest;

    // optional .test.PLevelResponse level_response = 6;
    public net.protoqueue.sample.proto.nano.TestProtos.PLevelResponse levelResponse;

    // optional .test.PGlobalBroadcast broadcast = 7;
    public net.protoqueue.sample.proto.nano.TestProtos.PGlobalBroadcast broadcast;

    public DslProto() {
      clear();
    }

    public DslProto clear() {
      uri = net.protoqueue.sample.proto.nano.TestProtos.kUserRequestUri;
      header = null;
      userRequest = null;
      userResponse = null;
      levelRequest = null;
      levelResponse = null;
      broadcast = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uri != net.protoqueue.sample.proto.nano.TestProtos.kUserRequestUri) {
        output.writeInt32(1, this.uri);
      }
      if (this.header != null) {
        output.writeMessage(2, this.header);
      }
      if (this.userRequest != null) {
        output.writeMessage(3, this.userRequest);
      }
      if (this.userResponse != null) {
        output.writeMessage(4, this.userResponse);
      }
      if (this.levelRequest != null) {
        output.writeMessage(5, this.levelRequest);
      }
      if (this.levelResponse != null) {
        output.writeMessage(6, this.levelResponse);
      }
      if (this.broadcast != null) {
        output.writeMessage(7, this.broadcast);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uri != net.protoqueue.sample.proto.nano.TestProtos.kUserRequestUri) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.uri);
      }
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.header);
      }
      if (this.userRequest != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.userRequest);
      }
      if (this.userResponse != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.userResponse);
      }
      if (this.levelRequest != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5, this.levelRequest);
      }
      if (this.levelResponse != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.levelResponse);
      }
      if (this.broadcast != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7, this.broadcast);
      }
      return size;
    }

    @Override
    public DslProto mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case net.protoqueue.sample.proto.nano.TestProtos.kUserRequestUri:
              case net.protoqueue.sample.proto.nano.TestProtos.kUserResponseUri:
              case net.protoqueue.sample.proto.nano.TestProtos.kLevelRequestUri:
              case net.protoqueue.sample.proto.nano.TestProtos.kLevelResponseUri:
              case net.protoqueue.sample.proto.nano.TestProtos.kGlobalBroadcast:
                this.uri = value;
                break;
            }
            break;
          }
          case 18: {
            if (this.header == null) {
              this.header = new net.protoqueue.sample.proto.nano.TestProtos.PHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 26: {
            if (this.userRequest == null) {
              this.userRequest = new net.protoqueue.sample.proto.nano.TestProtos.PUserRequest();
            }
            input.readMessage(this.userRequest);
            break;
          }
          case 34: {
            if (this.userResponse == null) {
              this.userResponse = new net.protoqueue.sample.proto.nano.TestProtos.PUserResponse();
            }
            input.readMessage(this.userResponse);
            break;
          }
          case 42: {
            if (this.levelRequest == null) {
              this.levelRequest = new net.protoqueue.sample.proto.nano.TestProtos.PLevelRequest();
            }
            input.readMessage(this.levelRequest);
            break;
          }
          case 50: {
            if (this.levelResponse == null) {
              this.levelResponse = new net.protoqueue.sample.proto.nano.TestProtos.PLevelResponse();
            }
            input.readMessage(this.levelResponse);
            break;
          }
          case 58: {
            if (this.broadcast == null) {
              this.broadcast = new net.protoqueue.sample.proto.nano.TestProtos.PGlobalBroadcast();
            }
            input.readMessage(this.broadcast);
            break;
          }
        }
      }
    }

    public static DslProto parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new DslProto(), data);
    }

    public static DslProto parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new DslProto().mergeFrom(input);
    }
  }

  public static final class PHeader extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PHeader[] _emptyArray;
    public static PHeader[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PHeader[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    // optional uint64 seqid = 2;
    public long seqid;

    // optional .test.Result result = 4;
    public net.protoqueue.sample.proto.nano.TestProtos.Result result;

    public PHeader() {
      clear();
    }

    public PHeader clear() {
      uid = 0L;
      seqid = 0L;
      result = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      if (this.seqid != 0L) {
        output.writeUInt64(2, this.seqid);
      }
      if (this.result != null) {
        output.writeMessage(4, this.result);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      if (this.seqid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(2, this.seqid);
      }
      if (this.result != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.result);
      }
      return size;
    }

    @Override
    public PHeader mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
          case 16: {
            this.seqid = input.readUInt64();
            break;
          }
          case 34: {
            if (this.result == null) {
              this.result = new net.protoqueue.sample.proto.nano.TestProtos.Result();
            }
            input.readMessage(this.result);
            break;
          }
        }
      }
    }

    public static PHeader parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PHeader(), data);
    }

    public static PHeader parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PHeader().mergeFrom(input);
    }
  }

  public static final class Result extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Result[] _emptyArray;
    public static Result[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Result[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .test.ResultType code = 1;
    public int code;

    // optional string res_msg = 2;
    public java.lang.String resMsg;

    public Result() {
      clear();
    }

    public Result clear() {
      code = net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk;
      resMsg = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.code != net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk) {
        output.writeInt32(1, this.code);
      }
      if (!this.resMsg.equals("")) {
        output.writeString(2, this.resMsg);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.code != net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.code);
      }
      if (!this.resMsg.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.resMsg);
      }
      return size;
    }

    @Override
    public Result mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case net.protoqueue.sample.proto.nano.TestProtos.kResultTypeOk:
              case net.protoqueue.sample.proto.nano.TestProtos.kResultTypeError:
                this.code = value;
                break;
            }
            break;
          }
          case 18: {
            this.resMsg = input.readString();
            break;
          }
        }
      }
    }

    public static Result parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Result(), data);
    }

    public static Result parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Result().mergeFrom(input);
    }
  }

  public static final class PUserRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUserRequest[] _emptyArray;
    public static PUserRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUserRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    public PUserRequest() {
      clear();
    }

    public PUserRequest clear() {
      uid = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      return size;
    }

    @Override
    public PUserRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
        }
      }
    }

    public static PUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUserRequest(), data);
    }

    public static PUserRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUserRequest().mergeFrom(input);
    }
  }

  public static final class PUserResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUserResponse[] _emptyArray;
    public static PUserResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUserResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    // optional string name = 2;
    public java.lang.String name;

    public PUserResponse() {
      clear();
    }

    public PUserResponse clear() {
      uid = 0L;
      name = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      return size;
    }

    @Override
    public PUserResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
        }
      }
    }

    public static PUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUserResponse(), data);
    }

    public static PUserResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUserResponse().mergeFrom(input);
    }
  }

  public static final class PGlobalBroadcast extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PGlobalBroadcast[] _emptyArray;
    public static PGlobalBroadcast[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PGlobalBroadcast[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string payload = 1;
    public java.lang.String payload;

    public PGlobalBroadcast() {
      clear();
    }

    public PGlobalBroadcast clear() {
      payload = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.payload.equals("")) {
        output.writeString(1, this.payload);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.payload.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.payload);
      }
      return size;
    }

    @Override
    public PGlobalBroadcast mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.payload = input.readString();
            break;
          }
        }
      }
    }

    public static PGlobalBroadcast parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PGlobalBroadcast(), data);
    }

    public static PGlobalBroadcast parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PGlobalBroadcast().mergeFrom(input);
    }
  }

  public static final class PLevelRequest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PLevelRequest[] _emptyArray;
    public static PLevelRequest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PLevelRequest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    public PLevelRequest() {
      clear();
    }

    public PLevelRequest clear() {
      uid = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      return size;
    }

    @Override
    public PLevelRequest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
        }
      }
    }

    public static PLevelRequest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PLevelRequest(), data);
    }

    public static PLevelRequest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PLevelRequest().mergeFrom(input);
    }
  }

  public static final class PLevelResponse extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PLevelResponse[] _emptyArray;
    public static PLevelResponse[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PLevelResponse[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional uint64 uid = 1;
    public long uid;

    // optional uint32 level = 2;
    public int level;

    public PLevelResponse() {
      clear();
    }

    public PLevelResponse clear() {
      uid = 0L;
      level = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uid != 0L) {
        output.writeUInt64(1, this.uid);
      }
      if (this.level != 0) {
        output.writeUInt32(2, this.level);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt64Size(1, this.uid);
      }
      if (this.level != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.level);
      }
      return size;
    }

    @Override
    public PLevelResponse mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.uid = input.readUInt64();
            break;
          }
          case 16: {
            this.level = input.readUInt32();
            break;
          }
        }
      }
    }

    public static PLevelResponse parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PLevelResponse(), data);
    }

    public static PLevelResponse parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PLevelResponse().mergeFrom(input);
    }
  }
}
