// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcApi {

  // enum CmdType
  public interface CmdType {
    public static final int CmdUnknown = 0;
    public static final int LogPull = 1;
  }

  // enum PrivacySettingType
  public interface PrivacySettingType {
    public static final int PrivacyTypeUnknown = 0;
    public static final int RecommendToFbFriend = 1;
    public static final int RecommendToGFriend = 2;
    public static final int RecommendToNear = 3;
  }

  public static final class SetPrivacySettingReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SetPrivacySettingReq[] _emptyArray;
    public static SetPrivacySettingReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SetPrivacySettingReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.api.PrivacySettingType type = 1;
    private int type_;
    public int getType() {
      return type_;
    }
    public SetPrivacySettingReq setType(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public SetPrivacySettingReq clearType() {
      type_ = com.woohoo.app.common.protocol.nano.WhSvcApi.PrivacySettingType.PrivacyTypeUnknown;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional bool status = 2;
    private boolean status_;
    public boolean getStatus() {
      return status_;
    }
    public SetPrivacySettingReq setStatus(boolean value) {
      status_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public SetPrivacySettingReq clearStatus() {
      status_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public SetPrivacySettingReq() {
      clear();
    }

    public SetPrivacySettingReq clear() {
      bitField0_ = 0;
      type_ = com.woohoo.app.common.protocol.nano.WhSvcApi.PrivacySettingType.PrivacyTypeUnknown;
      status_ = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, status_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, status_);
      }
      return size;
    }

    @Override
    public SetPrivacySettingReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcApi.PrivacySettingType.PrivacyTypeUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcApi.PrivacySettingType.RecommendToFbFriend:
              case com.woohoo.app.common.protocol.nano.WhSvcApi.PrivacySettingType.RecommendToGFriend:
              case com.woohoo.app.common.protocol.nano.WhSvcApi.PrivacySettingType.RecommendToNear:
                type_ = value;
                bitField0_ |= 0x00000001;
                break;
            }
            break;
          }
          case 16: {
            status_ = input.readBool();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static SetPrivacySettingReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SetPrivacySettingReq(), data);
    }

    public static SetPrivacySettingReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SetPrivacySettingReq().mergeFrom(input);
    }
  }

  public static final class SetPrivacySettingRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SetPrivacySettingRes[] _emptyArray;
    public static SetPrivacySettingRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SetPrivacySettingRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public SetPrivacySettingRes() {
      clear();
    }

    public SetPrivacySettingRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public SetPrivacySettingRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static SetPrivacySettingRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SetPrivacySettingRes(), data);
    }

    public static SetPrivacySettingRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SetPrivacySettingRes().mergeFrom(input);
    }
  }

  public static final class GetPrivacySettingReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetPrivacySettingReq[] _emptyArray;
    public static GetPrivacySettingReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetPrivacySettingReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public GetPrivacySettingReq() {
      clear();
    }

    public GetPrivacySettingReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public GetPrivacySettingReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static GetPrivacySettingReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetPrivacySettingReq(), data);
    }

    public static GetPrivacySettingReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetPrivacySettingReq().mergeFrom(input);
    }
  }

  public static final class GetPrivacySettingRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetPrivacySettingRes[] _emptyArray;
    public static GetPrivacySettingRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetPrivacySettingRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional bool recommendToFbFriend = 2;
    private boolean recommendToFbFriend_;
    public boolean getRecommendToFbFriend() {
      return recommendToFbFriend_;
    }
    public GetPrivacySettingRes setRecommendToFbFriend(boolean value) {
      recommendToFbFriend_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRecommendToFbFriend() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public GetPrivacySettingRes clearRecommendToFbFriend() {
      recommendToFbFriend_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional bool recommendToGFriend = 3;
    private boolean recommendToGFriend_;
    public boolean getRecommendToGFriend() {
      return recommendToGFriend_;
    }
    public GetPrivacySettingRes setRecommendToGFriend(boolean value) {
      recommendToGFriend_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasRecommendToGFriend() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public GetPrivacySettingRes clearRecommendToGFriend() {
      recommendToGFriend_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional bool recommendToNear = 4;
    private boolean recommendToNear_;
    public boolean getRecommendToNear() {
      return recommendToNear_;
    }
    public GetPrivacySettingRes setRecommendToNear(boolean value) {
      recommendToNear_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasRecommendToNear() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public GetPrivacySettingRes clearRecommendToNear() {
      recommendToNear_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public GetPrivacySettingRes() {
      clear();
    }

    public GetPrivacySettingRes clear() {
      bitField0_ = 0;
      header = null;
      recommendToFbFriend_ = false;
      recommendToGFriend_ = false;
      recommendToNear_ = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(2, recommendToFbFriend_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(3, recommendToGFriend_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(4, recommendToNear_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, recommendToFbFriend_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, recommendToGFriend_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(4, recommendToNear_);
      }
      return size;
    }

    @Override
    public GetPrivacySettingRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 16: {
            recommendToFbFriend_ = input.readBool();
            bitField0_ |= 0x00000001;
            break;
          }
          case 24: {
            recommendToGFriend_ = input.readBool();
            bitField0_ |= 0x00000002;
            break;
          }
          case 32: {
            recommendToNear_ = input.readBool();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static GetPrivacySettingRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetPrivacySettingRes(), data);
    }

    public static GetPrivacySettingRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetPrivacySettingRes().mergeFrom(input);
    }
  }

  public static final class CommandInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CommandInfo[] _emptyArray;
    public static CommandInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CommandInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string cmdId = 1;
    private java.lang.String cmdId_;
    @Nullable
    public java.lang.String getCmdId() {
      return cmdId_;
    }
    public CommandInfo setCmdId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      cmdId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasCmdId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CommandInfo clearCmdId() {
      cmdId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.api.CmdType cmdType = 2;
    private int cmdType_;
    public int getCmdType() {
      return cmdType_;
    }
    public CommandInfo setCmdType(int value) {
      cmdType_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasCmdType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public CommandInfo clearCmdType() {
      cmdType_ = com.woohoo.app.common.protocol.nano.WhSvcApi.CmdType.CmdUnknown;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional .wh.svc.api.LogCondition logCondition = 3;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcApi.LogCondition logCondition;

    public CommandInfo() {
      clear();
    }

    public CommandInfo clear() {
      bitField0_ = 0;
      cmdId_ = "";
      cmdType_ = com.woohoo.app.common.protocol.nano.WhSvcApi.CmdType.CmdUnknown;
      logCondition = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, cmdId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, cmdType_);
      }
      if (this.logCondition != null) {
        output.writeMessage(3, this.logCondition);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, cmdId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, cmdType_);
      }
      if (this.logCondition != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.logCondition);
      }
      return size;
    }

    @Override
    public CommandInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            cmdId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcApi.CmdType.CmdUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcApi.CmdType.LogPull:
                cmdType_ = value;
                bitField0_ |= 0x00000002;
                break;
            }
            break;
          }
          case 26: {
            if (this.logCondition == null) {
              this.logCondition = new com.woohoo.app.common.protocol.nano.WhSvcApi.LogCondition();
            }
            input.readMessage(this.logCondition);
            break;
          }
        }
      }
    }

    public static CommandInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CommandInfo(), data);
    }

    public static CommandInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CommandInfo().mergeFrom(input);
    }
  }

  public static final class LogCondition extends
      com.google.protobuf.nano.MessageNano {

    private static volatile LogCondition[] _emptyArray;
    public static LogCondition[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LogCondition[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 startTime = 1;
    private long startTime_;
    public long getStartTime() {
      return startTime_;
    }
    public LogCondition setStartTime(long value) {
      startTime_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasStartTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public LogCondition clearStartTime() {
      startTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 endTime = 2;
    private long endTime_;
    public long getEndTime() {
      return endTime_;
    }
    public LogCondition setEndTime(long value) {
      endTime_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public LogCondition clearEndTime() {
      endTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional bool containSdk = 3;
    private boolean containSdk_;
    public boolean getContainSdk() {
      return containSdk_;
    }
    public LogCondition setContainSdk(boolean value) {
      containSdk_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasContainSdk() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public LogCondition clearContainSdk() {
      containSdk_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public LogCondition() {
      clear();
    }

    public LogCondition clear() {
      bitField0_ = 0;
      startTime_ = 0L;
      endTime_ = 0L;
      containSdk_ = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, endTime_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, containSdk_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, startTime_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, endTime_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, containSdk_);
      }
      return size;
    }

    @Override
    public LogCondition mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            startTime_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            endTime_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            containSdk_ = input.readBool();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static LogCondition parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LogCondition(), data);
    }

    public static LogCondition parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LogCondition().mergeFrom(input);
    }
  }

  public static final class GetPendingCommandReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetPendingCommandReq[] _emptyArray;
    public static GetPendingCommandReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetPendingCommandReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public GetPendingCommandReq() {
      clear();
    }

    public GetPendingCommandReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public GetPendingCommandReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static GetPendingCommandReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetPendingCommandReq(), data);
    }

    public static GetPendingCommandReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetPendingCommandReq().mergeFrom(input);
    }
  }

  public static final class GetPendingCommandRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetPendingCommandRes[] _emptyArray;
    public static GetPendingCommandRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetPendingCommandRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // repeated .wh.svc.api.CommandInfo commandInfos = 2;
    public com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo[] commandInfos;

    public GetPendingCommandRes() {
      clear();
    }

    public GetPendingCommandRes clear() {
      header = null;
      commandInfos = com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (this.commandInfos != null && this.commandInfos.length > 0) {
        for (int i = 0; i < this.commandInfos.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo element = this.commandInfos[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (this.commandInfos != null && this.commandInfos.length > 0) {
        for (int i = 0; i < this.commandInfos.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo element = this.commandInfos[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }

    @Override
    public GetPendingCommandRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.commandInfos == null ? 0 : this.commandInfos.length;
            com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.commandInfos, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcApi.CommandInfo();
            input.readMessage(newArray[i]);
            this.commandInfos = newArray;
            break;
          }
        }
      }
    }

    public static GetPendingCommandRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetPendingCommandRes(), data);
    }

    public static GetPendingCommandRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetPendingCommandRes().mergeFrom(input);
    }
  }

  public static final class CommandCallbackReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CommandCallbackReq[] _emptyArray;
    public static CommandCallbackReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CommandCallbackReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string cmdId = 1;
    private java.lang.String cmdId_;
    @Nullable
    public java.lang.String getCmdId() {
      return cmdId_;
    }
    public CommandCallbackReq setCmdId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      cmdId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasCmdId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CommandCallbackReq clearCmdId() {
      cmdId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional bool ack = 2;
    private boolean ack_;
    public boolean getAck() {
      return ack_;
    }
    public CommandCallbackReq setAck(boolean value) {
      ack_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasAck() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public CommandCallbackReq clearAck() {
      ack_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional .wh.svc.api.LogResult logResult = 3;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcApi.LogResult logResult;

    public CommandCallbackReq() {
      clear();
    }

    public CommandCallbackReq clear() {
      bitField0_ = 0;
      cmdId_ = "";
      ack_ = false;
      logResult = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, cmdId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, ack_);
      }
      if (this.logResult != null) {
        output.writeMessage(3, this.logResult);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, cmdId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, ack_);
      }
      if (this.logResult != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.logResult);
      }
      return size;
    }

    @Override
    public CommandCallbackReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            cmdId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            ack_ = input.readBool();
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            if (this.logResult == null) {
              this.logResult = new com.woohoo.app.common.protocol.nano.WhSvcApi.LogResult();
            }
            input.readMessage(this.logResult);
            break;
          }
        }
      }
    }

    public static CommandCallbackReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CommandCallbackReq(), data);
    }

    public static CommandCallbackReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CommandCallbackReq().mergeFrom(input);
    }
  }

  public static final class LogResult extends
      com.google.protobuf.nano.MessageNano {

    private static volatile LogResult[] _emptyArray;
    public static LogResult[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new LogResult[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string logUrl = 1;
    private java.lang.String logUrl_;
    @Nullable
    public java.lang.String getLogUrl() {
      return logUrl_;
    }
    public LogResult setLogUrl(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      logUrl_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasLogUrl() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public LogResult clearLogUrl() {
      logUrl_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public LogResult() {
      clear();
    }

    public LogResult clear() {
      bitField0_ = 0;
      logUrl_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, logUrl_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, logUrl_);
      }
      return size;
    }

    @Override
    public LogResult mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            logUrl_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static LogResult parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new LogResult(), data);
    }

    public static LogResult parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new LogResult().mergeFrom(input);
    }
  }

  public static final class CommandCallbackRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CommandCallbackRes[] _emptyArray;
    public static CommandCallbackRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CommandCallbackRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public CommandCallbackRes() {
      clear();
    }

    public CommandCallbackRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public CommandCallbackRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static CommandCallbackRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CommandCallbackRes(), data);
    }

    public static CommandCallbackRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CommandCallbackRes().mergeFrom(input);
    }
  }
}
