// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcChatmatch {

  // enum NeedSex
  public interface NeedSex {
    public static final int Whatever = 0;
    public static final int NeedFemale = 1;
    public static final int NeedMale = 2;
  }

  public static final class GetMatchConfigReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetMatchConfigReq[] _emptyArray;
    public static GetMatchConfigReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetMatchConfigReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public GetMatchConfigReq() {
      clear();
    }

    public GetMatchConfigReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public GetMatchConfigReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static GetMatchConfigReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetMatchConfigReq(), data);
    }

    public static GetMatchConfigReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetMatchConfigReq().mergeFrom(input);
    }
  }

  public static final class GetMatchConfigRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetMatchConfigRes[] _emptyArray;
    public static GetMatchConfigRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetMatchConfigRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional int32 interval = 2;
    private int interval_;
    public int getInterval() {
      return interval_;
    }
    public GetMatchConfigRes setInterval(int value) {
      interval_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public GetMatchConfigRes clearInterval() {
      interval_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int32 matchDelay = 3;
    private int matchDelay_;
    public int getMatchDelay() {
      return matchDelay_;
    }
    public GetMatchConfigRes setMatchDelay(int value) {
      matchDelay_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasMatchDelay() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public GetMatchConfigRes clearMatchDelay() {
      matchDelay_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int32 acceptDuration = 4;
    private int acceptDuration_;
    public int getAcceptDuration() {
      return acceptDuration_;
    }
    public GetMatchConfigRes setAcceptDuration(int value) {
      acceptDuration_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasAcceptDuration() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public GetMatchConfigRes clearAcceptDuration() {
      acceptDuration_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // repeated string tips = 5;
    public java.lang.String[] tips;

    public GetMatchConfigRes() {
      clear();
    }

    public GetMatchConfigRes clear() {
      bitField0_ = 0;
      header = null;
      interval_ = 0;
      matchDelay_ = 0;
      acceptDuration_ = 0;
      tips = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, interval_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, matchDelay_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, acceptDuration_);
      }
      if (this.tips != null && this.tips.length > 0) {
        for (int i = 0; i < this.tips.length; i++) {
          java.lang.String element = this.tips[i];
          if (element != null) {
            output.writeString(5, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, interval_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, matchDelay_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, acceptDuration_);
      }
      if (this.tips != null && this.tips.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.tips.length; i++) {
          java.lang.String element = this.tips[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public GetMatchConfigRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 16: {
            interval_ = input.readInt32();
            bitField0_ |= 0x00000001;
            break;
          }
          case 24: {
            matchDelay_ = input.readInt32();
            bitField0_ |= 0x00000002;
            break;
          }
          case 32: {
            acceptDuration_ = input.readInt32();
            bitField0_ |= 0x00000004;
            break;
          }
          case 42: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.tips == null ? 0 : this.tips.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.tips, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.tips = newArray;
            break;
          }
        }
      }
    }

    public static GetMatchConfigRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetMatchConfigRes(), data);
    }

    public static GetMatchConfigRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetMatchConfigRes().mergeFrom(input);
    }
  }

  public static final class StartMatchReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile StartMatchReq[] _emptyArray;
    public static StartMatchReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StartMatchReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.Sex sex = 1;
    private int sex_;
    public int getSex() {
      return sex_;
    }
    public StartMatchReq setSex(int value) {
      sex_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasSex() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public StartMatchReq clearSex() {
      sex_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.chatmatch.NeedSex needSex = 2;
    private int needSex_;
    public int getNeedSex() {
      return needSex_;
    }
    public StartMatchReq setNeedSex(int value) {
      needSex_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasNeedSex() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public StartMatchReq clearNeedSex() {
      needSex_ = com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.Whatever;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int64 firstLoginTime = 3;
    private long firstLoginTime_;
    public long getFirstLoginTime() {
      return firstLoginTime_;
    }
    public StartMatchReq setFirstLoginTime(long value) {
      firstLoginTime_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasFirstLoginTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public StartMatchReq clearFirstLoginTime() {
      firstLoginTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional int32 age = 4;
    private int age_;
    public int getAge() {
      return age_;
    }
    public StartMatchReq setAge(int value) {
      age_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasAge() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public StartMatchReq clearAge() {
      age_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    // optional double latitude = 5;
    private double latitude_;
    public double getLatitude() {
      return latitude_;
    }
    public StartMatchReq setLatitude(double value) {
      latitude_ = value;
      bitField0_ |= 0x00000010;
      return this;
    }
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    public StartMatchReq clearLatitude() {
      latitude_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    // optional double longitude = 6;
    private double longitude_;
    public double getLongitude() {
      return longitude_;
    }
    public StartMatchReq setLongitude(double value) {
      longitude_ = value;
      bitField0_ |= 0x00000020;
      return this;
    }
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    public StartMatchReq clearLongitude() {
      longitude_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    public StartMatchReq() {
      clear();
    }

    public StartMatchReq clear() {
      bitField0_ = 0;
      sex_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown;
      needSex_ = com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.Whatever;
      firstLoginTime_ = 0L;
      age_ = 0;
      latitude_ = 0D;
      longitude_ = 0D;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, sex_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, needSex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, firstLoginTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, age_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeDouble(5, latitude_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeDouble(6, longitude_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, sex_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, needSex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, firstLoginTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, age_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(5, latitude_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(6, longitude_);
      }
      return size;
    }

    @Override
    public StartMatchReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.FeMale:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.Male:
                sex_ = value;
                bitField0_ |= 0x00000001;
                break;
            }
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.Whatever:
              case com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.NeedFemale:
              case com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.NeedMale:
                needSex_ = value;
                bitField0_ |= 0x00000002;
                break;
            }
            break;
          }
          case 24: {
            firstLoginTime_ = input.readInt64();
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            age_ = input.readInt32();
            bitField0_ |= 0x00000008;
            break;
          }
          case 41: {
            latitude_ = input.readDouble();
            bitField0_ |= 0x00000010;
            break;
          }
          case 49: {
            longitude_ = input.readDouble();
            bitField0_ |= 0x00000020;
            break;
          }
        }
      }
    }

    public static StartMatchReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new StartMatchReq(), data);
    }

    public static StartMatchReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StartMatchReq().mergeFrom(input);
    }
  }

  public static final class StartMatchRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile StartMatchRes[] _emptyArray;
    public static StartMatchRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StartMatchRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional int32 restrictedSeconds = 2;
    private int restrictedSeconds_;
    public int getRestrictedSeconds() {
      return restrictedSeconds_;
    }
    public StartMatchRes setRestrictedSeconds(int value) {
      restrictedSeconds_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRestrictedSeconds() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public StartMatchRes clearRestrictedSeconds() {
      restrictedSeconds_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public StartMatchRes() {
      clear();
    }

    public StartMatchRes clear() {
      bitField0_ = 0;
      header = null;
      restrictedSeconds_ = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, restrictedSeconds_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, restrictedSeconds_);
      }
      return size;
    }

    @Override
    public StartMatchRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 16: {
            restrictedSeconds_ = input.readInt32();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static StartMatchRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new StartMatchRes(), data);
    }

    public static StartMatchRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StartMatchRes().mergeFrom(input);
    }
  }

  public static final class MatchHeartbeatReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile MatchHeartbeatReq[] _emptyArray;
    public static MatchHeartbeatReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MatchHeartbeatReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.Sex sex = 1;
    private int sex_;
    public int getSex() {
      return sex_;
    }
    public MatchHeartbeatReq setSex(int value) {
      sex_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasSex() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public MatchHeartbeatReq clearSex() {
      sex_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.chatmatch.NeedSex needSex = 2;
    private int needSex_;
    public int getNeedSex() {
      return needSex_;
    }
    public MatchHeartbeatReq setNeedSex(int value) {
      needSex_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasNeedSex() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public MatchHeartbeatReq clearNeedSex() {
      needSex_ = com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.Whatever;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int64 firstLoginTime = 3;
    private long firstLoginTime_;
    public long getFirstLoginTime() {
      return firstLoginTime_;
    }
    public MatchHeartbeatReq setFirstLoginTime(long value) {
      firstLoginTime_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasFirstLoginTime() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public MatchHeartbeatReq clearFirstLoginTime() {
      firstLoginTime_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional int32 age = 4;
    private int age_;
    public int getAge() {
      return age_;
    }
    public MatchHeartbeatReq setAge(int value) {
      age_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasAge() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public MatchHeartbeatReq clearAge() {
      age_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    // optional double latitude = 5;
    private double latitude_;
    public double getLatitude() {
      return latitude_;
    }
    public MatchHeartbeatReq setLatitude(double value) {
      latitude_ = value;
      bitField0_ |= 0x00000010;
      return this;
    }
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    public MatchHeartbeatReq clearLatitude() {
      latitude_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    // optional double longitude = 6;
    private double longitude_;
    public double getLongitude() {
      return longitude_;
    }
    public MatchHeartbeatReq setLongitude(double value) {
      longitude_ = value;
      bitField0_ |= 0x00000020;
      return this;
    }
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    public MatchHeartbeatReq clearLongitude() {
      longitude_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    public MatchHeartbeatReq() {
      clear();
    }

    public MatchHeartbeatReq clear() {
      bitField0_ = 0;
      sex_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown;
      needSex_ = com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.Whatever;
      firstLoginTime_ = 0L;
      age_ = 0;
      latitude_ = 0D;
      longitude_ = 0D;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, sex_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, needSex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, firstLoginTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, age_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeDouble(5, latitude_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeDouble(6, longitude_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, sex_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, needSex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, firstLoginTime_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, age_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(5, latitude_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(6, longitude_);
      }
      return size;
    }

    @Override
    public MatchHeartbeatReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.FeMale:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.Male:
                sex_ = value;
                bitField0_ |= 0x00000001;
                break;
            }
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.Whatever:
              case com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.NeedFemale:
              case com.woohoo.app.common.protocol.nano.WhSvcChatmatch.NeedSex.NeedMale:
                needSex_ = value;
                bitField0_ |= 0x00000002;
                break;
            }
            break;
          }
          case 24: {
            firstLoginTime_ = input.readInt64();
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            age_ = input.readInt32();
            bitField0_ |= 0x00000008;
            break;
          }
          case 41: {
            latitude_ = input.readDouble();
            bitField0_ |= 0x00000010;
            break;
          }
          case 49: {
            longitude_ = input.readDouble();
            bitField0_ |= 0x00000020;
            break;
          }
        }
      }
    }

    public static MatchHeartbeatReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MatchHeartbeatReq(), data);
    }

    public static MatchHeartbeatReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MatchHeartbeatReq().mergeFrom(input);
    }
  }

  public static final class MatchHeartbeatRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile MatchHeartbeatRes[] _emptyArray;
    public static MatchHeartbeatRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MatchHeartbeatRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public MatchHeartbeatRes() {
      clear();
    }

    public MatchHeartbeatRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public MatchHeartbeatRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static MatchHeartbeatRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MatchHeartbeatRes(), data);
    }

    public static MatchHeartbeatRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MatchHeartbeatRes().mergeFrom(input);
    }
  }

  public static final class CancelMatchReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CancelMatchReq[] _emptyArray;
    public static CancelMatchReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CancelMatchReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public CancelMatchReq() {
      clear();
    }

    public CancelMatchReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public CancelMatchReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static CancelMatchReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CancelMatchReq(), data);
    }

    public static CancelMatchReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CancelMatchReq().mergeFrom(input);
    }
  }

  public static final class CancelMatchRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CancelMatchRes[] _emptyArray;
    public static CancelMatchRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CancelMatchRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional bool success = 2;
    private boolean success_;
    public boolean getSuccess() {
      return success_;
    }
    public CancelMatchRes setSuccess(boolean value) {
      success_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasSuccess() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CancelMatchRes clearSuccess() {
      success_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public CancelMatchRes() {
      clear();
    }

    public CancelMatchRes clear() {
      bitField0_ = 0;
      header = null;
      success_ = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(2, success_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, success_);
      }
      return size;
    }

    @Override
    public CancelMatchRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 16: {
            success_ = input.readBool();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static CancelMatchRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CancelMatchRes(), data);
    }

    public static CancelMatchRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CancelMatchRes().mergeFrom(input);
    }
  }

  public static final class MatchReadyNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile MatchReadyNotifyInfo[] _emptyArray;
    public static MatchReadyNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new MatchReadyNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string matchId = 1;
    private java.lang.String matchId_;
    @Nullable
    public java.lang.String getMatchId() {
      return matchId_;
    }
    public MatchReadyNotifyInfo setMatchId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      matchId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasMatchId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public MatchReadyNotifyInfo clearMatchId() {
      matchId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 hisUid = 2;
    private long hisUid_;
    public long getHisUid() {
      return hisUid_;
    }
    public MatchReadyNotifyInfo setHisUid(long value) {
      hisUid_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasHisUid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public MatchReadyNotifyInfo clearHisUid() {
      hisUid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int64 seqId = 3;
    private long seqId_;
    public long getSeqId() {
      return seqId_;
    }
    public MatchReadyNotifyInfo setSeqId(long value) {
      seqId_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public MatchReadyNotifyInfo clearSeqId() {
      seqId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public MatchReadyNotifyInfo() {
      clear();
    }

    public MatchReadyNotifyInfo clear() {
      bitField0_ = 0;
      matchId_ = "";
      hisUid_ = 0L;
      seqId_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, matchId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, hisUid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, seqId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, matchId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, hisUid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, seqId_);
      }
      return size;
    }

    @Override
    public MatchReadyNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            matchId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            hisUid_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            seqId_ = input.readInt64();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static MatchReadyNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new MatchReadyNotifyInfo(), data);
    }

    public static MatchReadyNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new MatchReadyNotifyInfo().mergeFrom(input);
    }
  }

  public static final class AcceptMatchReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AcceptMatchReq[] _emptyArray;
    public static AcceptMatchReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AcceptMatchReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string matchId = 1;
    private java.lang.String matchId_;
    @Nullable
    public java.lang.String getMatchId() {
      return matchId_;
    }
    public AcceptMatchReq setMatchId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      matchId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasMatchId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public AcceptMatchReq clearMatchId() {
      matchId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public AcceptMatchReq() {
      clear();
    }

    public AcceptMatchReq clear() {
      bitField0_ = 0;
      matchId_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, matchId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, matchId_);
      }
      return size;
    }

    @Override
    public AcceptMatchReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            matchId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static AcceptMatchReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AcceptMatchReq(), data);
    }

    public static AcceptMatchReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AcceptMatchReq().mergeFrom(input);
    }
  }

  public static final class AcceptMatchRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AcceptMatchRes[] _emptyArray;
    public static AcceptMatchRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AcceptMatchRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public AcceptMatchRes() {
      clear();
    }

    public AcceptMatchRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public AcceptMatchRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static AcceptMatchRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AcceptMatchRes(), data);
    }

    public static AcceptMatchRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AcceptMatchRes().mergeFrom(input);
    }
  }

  public static final class RejectMatchReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RejectMatchReq[] _emptyArray;
    public static RejectMatchReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RejectMatchReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string matchId = 1;
    private java.lang.String matchId_;
    @Nullable
    public java.lang.String getMatchId() {
      return matchId_;
    }
    public RejectMatchReq setMatchId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      matchId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasMatchId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public RejectMatchReq clearMatchId() {
      matchId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional bool reInQueue = 2;
    private boolean reInQueue_;
    public boolean getReInQueue() {
      return reInQueue_;
    }
    public RejectMatchReq setReInQueue(boolean value) {
      reInQueue_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasReInQueue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public RejectMatchReq clearReInQueue() {
      reInQueue_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional bool notBlacklist = 3;
    private boolean notBlacklist_;
    public boolean getNotBlacklist() {
      return notBlacklist_;
    }
    public RejectMatchReq setNotBlacklist(boolean value) {
      notBlacklist_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasNotBlacklist() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public RejectMatchReq clearNotBlacklist() {
      notBlacklist_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public RejectMatchReq() {
      clear();
    }

    public RejectMatchReq clear() {
      bitField0_ = 0;
      matchId_ = "";
      reInQueue_ = false;
      notBlacklist_ = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, matchId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, reInQueue_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, notBlacklist_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, matchId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, reInQueue_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, notBlacklist_);
      }
      return size;
    }

    @Override
    public RejectMatchReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            matchId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            reInQueue_ = input.readBool();
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            notBlacklist_ = input.readBool();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static RejectMatchReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RejectMatchReq(), data);
    }

    public static RejectMatchReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RejectMatchReq().mergeFrom(input);
    }
  }

  public static final class RejectMatchRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RejectMatchRes[] _emptyArray;
    public static RejectMatchRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RejectMatchRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public RejectMatchRes() {
      clear();
    }

    public RejectMatchRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public RejectMatchRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static RejectMatchRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RejectMatchRes(), data);
    }

    public static RejectMatchRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RejectMatchRes().mergeFrom(input);
    }
  }

  public static final class ReInMatchingNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReInMatchingNotifyInfo[] _emptyArray;
    public static ReInMatchingNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReInMatchingNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 uid = 1;
    private long uid_;
    public long getUid() {
      return uid_;
    }
    public ReInMatchingNotifyInfo setUid(long value) {
      uid_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public ReInMatchingNotifyInfo clearUid() {
      uid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 seqId = 2;
    private long seqId_;
    public long getSeqId() {
      return seqId_;
    }
    public ReInMatchingNotifyInfo setSeqId(long value) {
      seqId_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public ReInMatchingNotifyInfo clearSeqId() {
      seqId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public ReInMatchingNotifyInfo() {
      clear();
    }

    public ReInMatchingNotifyInfo clear() {
      bitField0_ = 0;
      uid_ = 0L;
      seqId_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, seqId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, seqId_);
      }
      return size;
    }

    @Override
    public ReInMatchingNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            uid_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            seqId_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static ReInMatchingNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReInMatchingNotifyInfo(), data);
    }

    public static ReInMatchingNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReInMatchingNotifyInfo().mergeFrom(input);
    }
  }

  public static final class InviteUserReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile InviteUserReq[] _emptyArray;
    public static InviteUserReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new InviteUserReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 invitee = 1;
    private long invitee_;
    public long getInvitee() {
      return invitee_;
    }
    public InviteUserReq setInvitee(long value) {
      invitee_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitee() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public InviteUserReq clearInvitee() {
      invitee_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public InviteUserReq() {
      clear();
    }

    public InviteUserReq clear() {
      bitField0_ = 0;
      invitee_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, invitee_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, invitee_);
      }
      return size;
    }

    @Override
    public InviteUserReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            invitee_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static InviteUserReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new InviteUserReq(), data);
    }

    public static InviteUserReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new InviteUserReq().mergeFrom(input);
    }
  }

  public static final class InviteUserRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile InviteUserRes[] _emptyArray;
    public static InviteUserRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new InviteUserRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional string invitationId = 2;
    private java.lang.String invitationId_;
    @Nullable
    public java.lang.String getInvitationId() {
      return invitationId_;
    }
    public InviteUserRes setInvitationId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      invitationId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public InviteUserRes clearInvitationId() {
      invitationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 expireTimestamp = 3;
    private long expireTimestamp_;
    public long getExpireTimestamp() {
      return expireTimestamp_;
    }
    public InviteUserRes setExpireTimestamp(long value) {
      expireTimestamp_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasExpireTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public InviteUserRes clearExpireTimestamp() {
      expireTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public InviteUserRes() {
      clear();
    }

    public InviteUserRes clear() {
      bitField0_ = 0;
      header = null;
      invitationId_ = "";
      expireTimestamp_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(2, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(3, expireTimestamp_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, expireTimestamp_);
      }
      return size;
    }

    @Override
    public InviteUserRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 18: {
            invitationId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 24: {
            expireTimestamp_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static InviteUserRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new InviteUserRes(), data);
    }

    public static InviteUserRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new InviteUserRes().mergeFrom(input);
    }
  }

  public static final class AcceptInvitationReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AcceptInvitationReq[] _emptyArray;
    public static AcceptInvitationReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AcceptInvitationReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string invitationId = 1;
    private java.lang.String invitationId_;
    @Nullable
    public java.lang.String getInvitationId() {
      return invitationId_;
    }
    public AcceptInvitationReq setInvitationId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      invitationId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public AcceptInvitationReq clearInvitationId() {
      invitationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public AcceptInvitationReq() {
      clear();
    }

    public AcceptInvitationReq clear() {
      bitField0_ = 0;
      invitationId_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, invitationId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, invitationId_);
      }
      return size;
    }

    @Override
    public AcceptInvitationReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            invitationId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static AcceptInvitationReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AcceptInvitationReq(), data);
    }

    public static AcceptInvitationReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AcceptInvitationReq().mergeFrom(input);
    }
  }

  public static final class AcceptInvitationRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AcceptInvitationRes[] _emptyArray;
    public static AcceptInvitationRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AcceptInvitationRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public AcceptInvitationRes() {
      clear();
    }

    public AcceptInvitationRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public AcceptInvitationRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static AcceptInvitationRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AcceptInvitationRes(), data);
    }

    public static AcceptInvitationRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AcceptInvitationRes().mergeFrom(input);
    }
  }

  public static final class RejectInvitationReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RejectInvitationReq[] _emptyArray;
    public static RejectInvitationReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RejectInvitationReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string invitationId = 1;
    private java.lang.String invitationId_;
    @Nullable
    public java.lang.String getInvitationId() {
      return invitationId_;
    }
    public RejectInvitationReq setInvitationId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      invitationId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public RejectInvitationReq clearInvitationId() {
      invitationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public RejectInvitationReq() {
      clear();
    }

    public RejectInvitationReq clear() {
      bitField0_ = 0;
      invitationId_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, invitationId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, invitationId_);
      }
      return size;
    }

    @Override
    public RejectInvitationReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            invitationId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static RejectInvitationReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RejectInvitationReq(), data);
    }

    public static RejectInvitationReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RejectInvitationReq().mergeFrom(input);
    }
  }

  public static final class RejectInvitationRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RejectInvitationRes[] _emptyArray;
    public static RejectInvitationRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RejectInvitationRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public RejectInvitationRes() {
      clear();
    }

    public RejectInvitationRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public RejectInvitationRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static RejectInvitationRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RejectInvitationRes(), data);
    }

    public static RejectInvitationRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RejectInvitationRes().mergeFrom(input);
    }
  }

  public static final class CancelInvitationNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CancelInvitationNotifyInfo[] _emptyArray;
    public static CancelInvitationNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CancelInvitationNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string invitationId = 1;
    private java.lang.String invitationId_;
    @Nullable
    public java.lang.String getInvitationId() {
      return invitationId_;
    }
    public CancelInvitationNotifyInfo setInvitationId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      invitationId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CancelInvitationNotifyInfo clearInvitationId() {
      invitationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 inviter = 2;
    private long inviter_;
    public long getInviter() {
      return inviter_;
    }
    public CancelInvitationNotifyInfo setInviter(long value) {
      inviter_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasInviter() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public CancelInvitationNotifyInfo clearInviter() {
      inviter_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public CancelInvitationNotifyInfo() {
      clear();
    }

    public CancelInvitationNotifyInfo clear() {
      bitField0_ = 0;
      invitationId_ = "";
      inviter_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, inviter_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, inviter_);
      }
      return size;
    }

    @Override
    public CancelInvitationNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            invitationId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            inviter_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static CancelInvitationNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CancelInvitationNotifyInfo(), data);
    }

    public static CancelInvitationNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CancelInvitationNotifyInfo().mergeFrom(input);
    }
  }

  public static final class RejectInvitationNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RejectInvitationNotifyInfo[] _emptyArray;
    public static RejectInvitationNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RejectInvitationNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string invitationId = 1;
    private java.lang.String invitationId_;
    @Nullable
    public java.lang.String getInvitationId() {
      return invitationId_;
    }
    public RejectInvitationNotifyInfo setInvitationId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      invitationId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public RejectInvitationNotifyInfo clearInvitationId() {
      invitationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 invitee = 2;
    private long invitee_;
    public long getInvitee() {
      return invitee_;
    }
    public RejectInvitationNotifyInfo setInvitee(long value) {
      invitee_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasInvitee() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public RejectInvitationNotifyInfo clearInvitee() {
      invitee_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public RejectInvitationNotifyInfo() {
      clear();
    }

    public RejectInvitationNotifyInfo clear() {
      bitField0_ = 0;
      invitationId_ = "";
      invitee_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, invitee_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, invitee_);
      }
      return size;
    }

    @Override
    public RejectInvitationNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            invitationId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            invitee_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static RejectInvitationNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RejectInvitationNotifyInfo(), data);
    }

    public static RejectInvitationNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RejectInvitationNotifyInfo().mergeFrom(input);
    }
  }

  public static final class AcceptInvitationNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AcceptInvitationNotifyInfo[] _emptyArray;
    public static AcceptInvitationNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AcceptInvitationNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string invitationId = 1;
    private java.lang.String invitationId_;
    @Nullable
    public java.lang.String getInvitationId() {
      return invitationId_;
    }
    public AcceptInvitationNotifyInfo setInvitationId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      invitationId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public AcceptInvitationNotifyInfo clearInvitationId() {
      invitationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 invitee = 2;
    private long invitee_;
    public long getInvitee() {
      return invitee_;
    }
    public AcceptInvitationNotifyInfo setInvitee(long value) {
      invitee_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasInvitee() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public AcceptInvitationNotifyInfo clearInvitee() {
      invitee_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public AcceptInvitationNotifyInfo() {
      clear();
    }

    public AcceptInvitationNotifyInfo clear() {
      bitField0_ = 0;
      invitationId_ = "";
      invitee_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, invitee_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, invitationId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, invitee_);
      }
      return size;
    }

    @Override
    public AcceptInvitationNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            invitationId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            invitee_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static AcceptInvitationNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AcceptInvitationNotifyInfo(), data);
    }

    public static AcceptInvitationNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AcceptInvitationNotifyInfo().mergeFrom(input);
    }
  }

  public static final class CancelInvitationReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CancelInvitationReq[] _emptyArray;
    public static CancelInvitationReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CancelInvitationReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string invitationId = 1;
    private java.lang.String invitationId_;
    @Nullable
    public java.lang.String getInvitationId() {
      return invitationId_;
    }
    public CancelInvitationReq setInvitationId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      invitationId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInvitationId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CancelInvitationReq clearInvitationId() {
      invitationId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public CancelInvitationReq() {
      clear();
    }

    public CancelInvitationReq clear() {
      bitField0_ = 0;
      invitationId_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, invitationId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, invitationId_);
      }
      return size;
    }

    @Override
    public CancelInvitationReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            invitationId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static CancelInvitationReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CancelInvitationReq(), data);
    }

    public static CancelInvitationReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CancelInvitationReq().mergeFrom(input);
    }
  }

  public static final class CancelInvitationRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CancelInvitationRes[] _emptyArray;
    public static CancelInvitationRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CancelInvitationRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public CancelInvitationRes() {
      clear();
    }

    public CancelInvitationRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public CancelInvitationRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static CancelInvitationRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CancelInvitationRes(), data);
    }

    public static CancelInvitationRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CancelInvitationRes().mergeFrom(input);
    }
  }
}
