// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcUserOnline {

  public static final class StartHeartbeatReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile StartHeartbeatReq[] _emptyArray;
    public static StartHeartbeatReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StartHeartbeatReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public StartHeartbeatReq() {
      clear();
    }

    public StartHeartbeatReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public StartHeartbeatReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static StartHeartbeatReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new StartHeartbeatReq(), data);
    }

    public static StartHeartbeatReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StartHeartbeatReq().mergeFrom(input);
    }
  }

  public static final class StartHeartbeatRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile StartHeartbeatRes[] _emptyArray;
    public static StartHeartbeatRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StartHeartbeatRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional int64 interval = 2;
    private long interval_;
    public long getInterval() {
      return interval_;
    }
    public StartHeartbeatRes setInterval(long value) {
      interval_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public StartHeartbeatRes clearInterval() {
      interval_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public StartHeartbeatRes() {
      clear();
    }

    public StartHeartbeatRes clear() {
      bitField0_ = 0;
      header = null;
      interval_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(2, interval_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, interval_);
      }
      return size;
    }

    @Override
    public StartHeartbeatRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 16: {
            interval_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static StartHeartbeatRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new StartHeartbeatRes(), data);
    }

    public static StartHeartbeatRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StartHeartbeatRes().mergeFrom(input);
    }
  }

  public static final class HeartbeatReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HeartbeatReq[] _emptyArray;
    public static HeartbeatReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HeartbeatReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public HeartbeatReq() {
      clear();
    }

    public HeartbeatReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public HeartbeatReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static HeartbeatReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HeartbeatReq(), data);
    }

    public static HeartbeatReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HeartbeatReq().mergeFrom(input);
    }
  }

  public static final class HeartbeatRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile HeartbeatRes[] _emptyArray;
    public static HeartbeatRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new HeartbeatRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public HeartbeatRes() {
      clear();
    }

    public HeartbeatRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public HeartbeatRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static HeartbeatRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new HeartbeatRes(), data);
    }

    public static HeartbeatRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new HeartbeatRes().mergeFrom(input);
    }
  }

  public static final class UserBizStatus extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UserBizStatus[] _emptyArray;
    public static UserBizStatus[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UserBizStatus[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string bizType = 1;
    private java.lang.String bizType_;
    @Nullable
    public java.lang.String getBizType() {
      return bizType_;
    }
    public UserBizStatus setBizType(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      bizType_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasBizType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public UserBizStatus clearBizType() {
      bizType_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 status = 2;
    private long status_;
    public long getStatus() {
      return status_;
    }
    public UserBizStatus setStatus(long value) {
      status_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public UserBizStatus clearStatus() {
      status_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public UserBizStatus() {
      clear();
    }

    public UserBizStatus clear() {
      bitField0_ = 0;
      bizType_ = "";
      status_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, bizType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, status_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, bizType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, status_);
      }
      return size;
    }

    @Override
    public UserBizStatus mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            bizType_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            status_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static UserBizStatus parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UserBizStatus(), data);
    }

    public static UserBizStatus parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UserBizStatus().mergeFrom(input);
    }
  }

  public static final class UserOnlineStatus extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UserOnlineStatus[] _emptyArray;
    public static UserOnlineStatus[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UserOnlineStatus[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional bool online = 1;
    private boolean online_;
    public boolean getOnline() {
      return online_;
    }
    public UserOnlineStatus setOnline(boolean value) {
      online_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasOnline() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public UserOnlineStatus clearOnline() {
      online_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // repeated .wh.svc.online.UserBizStatus status = 2;
    public com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus[] status;

    // optional int64 latestLoginTimestamp = 3;
    private long latestLoginTimestamp_;
    public long getLatestLoginTimestamp() {
      return latestLoginTimestamp_;
    }
    public UserOnlineStatus setLatestLoginTimestamp(long value) {
      latestLoginTimestamp_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasLatestLoginTimestamp() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public UserOnlineStatus clearLatestLoginTimestamp() {
      latestLoginTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public UserOnlineStatus() {
      clear();
    }

    public UserOnlineStatus clear() {
      bitField0_ = 0;
      online_ = false;
      status = com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus.emptyArray();
      latestLoginTimestamp_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, online_);
      }
      if (this.status != null && this.status.length > 0) {
        for (int i = 0; i < this.status.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus element = this.status[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(3, latestLoginTimestamp_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, online_);
      }
      if (this.status != null && this.status.length > 0) {
        for (int i = 0; i < this.status.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus element = this.status[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, latestLoginTimestamp_);
      }
      return size;
    }

    @Override
    public UserOnlineStatus mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            online_ = input.readBool();
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.status == null ? 0 : this.status.length;
            com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.status, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserBizStatus();
            input.readMessage(newArray[i]);
            this.status = newArray;
            break;
          }
          case 24: {
            latestLoginTimestamp_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static UserOnlineStatus parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UserOnlineStatus(), data);
    }

    public static UserOnlineStatus parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UserOnlineStatus().mergeFrom(input);
    }
  }

  public static final class BatchGetUserOnlineStatusReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BatchGetUserOnlineStatusReq[] _emptyArray;
    public static BatchGetUserOnlineStatusReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BatchGetUserOnlineStatusReq[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int64 uidList = 1;
    public long[] uidList;

    public BatchGetUserOnlineStatusReq() {
      clear();
    }

    public BatchGetUserOnlineStatusReq clear() {
      uidList = com.google.protobuf.nano.WireFormatNano.EMPTY_LONG_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uidList != null && this.uidList.length > 0) {
        for (int i = 0; i < this.uidList.length; i++) {
          output.writeInt64(1, this.uidList[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uidList != null && this.uidList.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.uidList.length; i++) {
          long element = this.uidList[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.uidList.length;
      }
      return size;
    }

    @Override
    public BatchGetUserOnlineStatusReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.uidList == null ? 0 : this.uidList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.uidList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt64();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt64();
            this.uidList = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt64();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.uidList == null ? 0 : this.uidList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.uidList, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt64();
            }
            this.uidList = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static BatchGetUserOnlineStatusReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BatchGetUserOnlineStatusReq(), data);
    }

    public static BatchGetUserOnlineStatusReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BatchGetUserOnlineStatusReq().mergeFrom(input);
    }
  }

  public static final class BatchGetUserOnlineStatusRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BatchGetUserOnlineStatusRes[] _emptyArray;
    public static BatchGetUserOnlineStatusRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BatchGetUserOnlineStatusRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // map<int64, .wh.svc.online.UserOnlineStatus> statusMap = 2;
    public java.util.Map<java.lang.Long, com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserOnlineStatus> statusMap;

    public BatchGetUserOnlineStatusRes() {
      clear();
    }

    public BatchGetUserOnlineStatusRes clear() {
      header = null;
      statusMap = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (this.statusMap != null) {
        com.google.protobuf.nano.InternalNano.serializeMapField(
          output, this.statusMap, 2,
        com.google.protobuf.nano.InternalNano.TYPE_INT64,
        com.google.protobuf.nano.InternalNano.TYPE_MESSAGE);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (this.statusMap != null) {
        size += com.google.protobuf.nano.InternalNano.computeMapFieldSize(
          this.statusMap, 2,
        com.google.protobuf.nano.InternalNano.TYPE_INT64,
        com.google.protobuf.nano.InternalNano.TYPE_MESSAGE);
      }
      return size;
    }

    @Override
    public BatchGetUserOnlineStatusRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      com.google.protobuf.nano.MapFactories.MapFactory mapFactory =
        com.google.protobuf.nano.MapFactories.getMapFactory();
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 18: {
            this.statusMap = com.google.protobuf.nano.InternalNano.mergeMapEntry(
              input, this.statusMap, mapFactory,
              com.google.protobuf.nano.InternalNano.TYPE_INT64,
              com.google.protobuf.nano.InternalNano.TYPE_MESSAGE,
              new com.woohoo.app.common.protocol.nano.WhSvcUserOnline.UserOnlineStatus(),
              8, 18);

            break;
          }
        }
      }
    }

    public static BatchGetUserOnlineStatusRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BatchGetUserOnlineStatusRes(), data);
    }

    public static BatchGetUserOnlineStatusRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BatchGetUserOnlineStatusRes().mergeFrom(input);
    }
  }
}
