// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcTacit {

  // enum QuestionType
  public interface QuestionType {
    public static final int Unknown = 0;
    public static final int TEXT = 1;
    public static final int IMG = 2;
  }

  public static final class AnswerReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AnswerReq[] _emptyArray;
    public static AnswerReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AnswerReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string roundId = 1;
    private java.lang.String roundId_;
    @Nullable
    public java.lang.String getRoundId() {
      return roundId_;
    }
    public AnswerReq setRoundId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      roundId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public AnswerReq clearRoundId() {
      roundId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 questionId = 2;
    private long questionId_;
    public long getQuestionId() {
      return questionId_;
    }
    public AnswerReq setQuestionId(long value) {
      questionId_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasQuestionId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public AnswerReq clearQuestionId() {
      questionId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int64 answerId = 3;
    private long answerId_;
    public long getAnswerId() {
      return answerId_;
    }
    public AnswerReq setAnswerId(long value) {
      answerId_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasAnswerId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public AnswerReq clearAnswerId() {
      answerId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional int32 questionOrder = 4;
    private int questionOrder_;
    public int getQuestionOrder() {
      return questionOrder_;
    }
    public AnswerReq setQuestionOrder(int value) {
      questionOrder_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasQuestionOrder() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public AnswerReq clearQuestionOrder() {
      questionOrder_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public AnswerReq() {
      clear();
    }

    public AnswerReq clear() {
      bitField0_ = 0;
      roundId_ = "";
      questionId_ = 0L;
      answerId_ = 0L;
      questionOrder_ = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, questionId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, answerId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, questionOrder_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, questionId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, answerId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, questionOrder_);
      }
      return size;
    }

    @Override
    public AnswerReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            roundId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            questionId_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            answerId_ = input.readInt64();
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            questionOrder_ = input.readInt32();
            bitField0_ |= 0x00000008;
            break;
          }
        }
      }
    }

    public static AnswerReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AnswerReq(), data);
    }

    public static AnswerReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AnswerReq().mergeFrom(input);
    }
  }

  public static final class AnswerRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile AnswerRes[] _emptyArray;
    public static AnswerRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AnswerRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public AnswerRes() {
      clear();
    }

    public AnswerRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public AnswerRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static AnswerRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new AnswerRes(), data);
    }

    public static AnswerRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AnswerRes().mergeFrom(input);
    }
  }

  public static final class TacitTitleReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TacitTitleReq[] _emptyArray;
    public static TacitTitleReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TacitTitleReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 targetUid = 1;
    private long targetUid_;
    public long getTargetUid() {
      return targetUid_;
    }
    public TacitTitleReq setTargetUid(long value) {
      targetUid_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasTargetUid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public TacitTitleReq clearTargetUid() {
      targetUid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public TacitTitleReq() {
      clear();
    }

    public TacitTitleReq clear() {
      bitField0_ = 0;
      targetUid_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, targetUid_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, targetUid_);
      }
      return size;
    }

    @Override
    public TacitTitleReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            targetUid_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static TacitTitleReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TacitTitleReq(), data);
    }

    public static TacitTitleReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TacitTitleReq().mergeFrom(input);
    }
  }

  public static final class TacitTitleRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile TacitTitleRes[] _emptyArray;
    public static TacitTitleRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new TacitTitleRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional int64 matchDegree = 2;
    private long matchDegree_;
    public long getMatchDegree() {
      return matchDegree_;
    }
    public TacitTitleRes setMatchDegree(long value) {
      matchDegree_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasMatchDegree() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public TacitTitleRes clearMatchDegree() {
      matchDegree_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional string title = 3;
    private java.lang.String title_;
    @Nullable
    public java.lang.String getTitle() {
      return title_;
    }
    public TacitTitleRes setTitle(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      title_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public TacitTitleRes clearTitle() {
      title_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public TacitTitleRes() {
      clear();
    }

    public TacitTitleRes clear() {
      bitField0_ = 0;
      header = null;
      matchDegree_ = 0L;
      title_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(2, matchDegree_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeString(3, title_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, matchDegree_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, title_);
      }
      return size;
    }

    @Override
    public TacitTitleRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 16: {
            matchDegree_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 26: {
            title_ = input.readString();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static TacitTitleRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new TacitTitleRes(), data);
    }

    public static TacitTitleRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new TacitTitleRes().mergeFrom(input);
    }
  }

  public static final class GetTacitBasicInfoReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetTacitBasicInfoReq[] _emptyArray;
    public static GetTacitBasicInfoReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetTacitBasicInfoReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string roundId = 1;
    private java.lang.String roundId_;
    @Nullable
    public java.lang.String getRoundId() {
      return roundId_;
    }
    public GetTacitBasicInfoReq setRoundId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      roundId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public GetTacitBasicInfoReq clearRoundId() {
      roundId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public GetTacitBasicInfoReq() {
      clear();
    }

    public GetTacitBasicInfoReq clear() {
      bitField0_ = 0;
      roundId_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, roundId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, roundId_);
      }
      return size;
    }

    @Override
    public GetTacitBasicInfoReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            roundId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static GetTacitBasicInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetTacitBasicInfoReq(), data);
    }

    public static GetTacitBasicInfoReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetTacitBasicInfoReq().mergeFrom(input);
    }
  }

  public static final class GetTacitBasicInfoRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetTacitBasicInfoRes[] _emptyArray;
    public static GetTacitBasicInfoRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetTacitBasicInfoRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional string roundId = 2;
    private java.lang.String roundId_;
    @Nullable
    public java.lang.String getRoundId() {
      return roundId_;
    }
    public GetTacitBasicInfoRes setRoundId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      roundId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public GetTacitBasicInfoRes clearRoundId() {
      roundId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int32 questionCount = 3;
    private int questionCount_;
    public int getQuestionCount() {
      return questionCount_;
    }
    public GetTacitBasicInfoRes setQuestionCount(int value) {
      questionCount_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasQuestionCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public GetTacitBasicInfoRes clearQuestionCount() {
      questionCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public GetTacitBasicInfoRes() {
      clear();
    }

    public GetTacitBasicInfoRes clear() {
      bitField0_ = 0;
      header = null;
      roundId_ = "";
      questionCount_ = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(2, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, questionCount_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, questionCount_);
      }
      return size;
    }

    @Override
    public GetTacitBasicInfoRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 18: {
            roundId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 24: {
            questionCount_ = input.readInt32();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static GetTacitBasicInfoRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetTacitBasicInfoRes(), data);
    }

    public static GetTacitBasicInfoRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetTacitBasicInfoRes().mergeFrom(input);
    }
  }

  public static final class Question extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Question[] _emptyArray;
    public static Question[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Question[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 questionId = 1;
    private long questionId_;
    public long getQuestionId() {
      return questionId_;
    }
    public Question setQuestionId(long value) {
      questionId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasQuestionId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public Question clearQuestionId() {
      questionId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int32 questionOrder = 2;
    private int questionOrder_;
    public int getQuestionOrder() {
      return questionOrder_;
    }
    public Question setQuestionOrder(int value) {
      questionOrder_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasQuestionOrder() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public Question clearQuestionOrder() {
      questionOrder_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int32 remainMs = 3;
    private int remainMs_;
    public int getRemainMs() {
      return remainMs_;
    }
    public Question setRemainMs(int value) {
      remainMs_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasRemainMs() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public Question clearRemainMs() {
      remainMs_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional .wh.svc.tacit.QuestionType type = 4;
    private int type_;
    public int getType() {
      return type_;
    }
    public Question setType(int value) {
      type_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public Question clearType() {
      type_ = com.woohoo.app.common.protocol.nano.WhSvcTacit.QuestionType.Unknown;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    // optional string content = 5;
    private java.lang.String content_;
    @Nullable
    public java.lang.String getContent() {
      return content_;
    }
    public Question setContent(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      content_ = value;
      bitField0_ |= 0x00000010;
      return this;
    }
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    public Question clearContent() {
      content_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    // repeated .wh.svc.tacit.Answer answers = 6;
    public com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer[] answers;

    public Question() {
      clear();
    }

    public Question clear() {
      bitField0_ = 0;
      questionId_ = 0L;
      questionOrder_ = 0;
      remainMs_ = 0;
      type_ = com.woohoo.app.common.protocol.nano.WhSvcTacit.QuestionType.Unknown;
      content_ = "";
      answers = com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, questionId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, questionOrder_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, remainMs_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, type_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeString(5, content_);
      }
      if (this.answers != null && this.answers.length > 0) {
        for (int i = 0; i < this.answers.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer element = this.answers[i];
          if (element != null) {
            output.writeMessage(6, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, questionId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, questionOrder_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, remainMs_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(4, type_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, content_);
      }
      if (this.answers != null && this.answers.length > 0) {
        for (int i = 0; i < this.answers.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer element = this.answers[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(6, element);
          }
        }
      }
      return size;
    }

    @Override
    public Question mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            questionId_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            questionOrder_ = input.readInt32();
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            remainMs_ = input.readInt32();
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcTacit.QuestionType.Unknown:
              case com.woohoo.app.common.protocol.nano.WhSvcTacit.QuestionType.TEXT:
              case com.woohoo.app.common.protocol.nano.WhSvcTacit.QuestionType.IMG:
                type_ = value;
                bitField0_ |= 0x00000008;
                break;
            }
            break;
          }
          case 42: {
            content_ = input.readString();
            bitField0_ |= 0x00000010;
            break;
          }
          case 50: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 50);
            int i = this.answers == null ? 0 : this.answers.length;
            com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.answers, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcTacit.Answer();
            input.readMessage(newArray[i]);
            this.answers = newArray;
            break;
          }
        }
      }
    }

    public static Question parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Question(), data);
    }

    public static Question parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Question().mergeFrom(input);
    }
  }

  public static final class Answer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Answer[] _emptyArray;
    public static Answer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Answer[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 answerId = 1;
    private long answerId_;
    public long getAnswerId() {
      return answerId_;
    }
    public Answer setAnswerId(long value) {
      answerId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasAnswerId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public Answer clearAnswerId() {
      answerId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional string content = 2;
    private java.lang.String content_;
    @Nullable
    public java.lang.String getContent() {
      return content_;
    }
    public Answer setContent(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      content_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public Answer clearContent() {
      content_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Answer() {
      clear();
    }

    public Answer clear() {
      bitField0_ = 0;
      answerId_ = 0L;
      content_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, answerId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeString(2, content_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, answerId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, content_);
      }
      return size;
    }

    @Override
    public Answer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            answerId_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            content_ = input.readString();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static Answer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Answer(), data);
    }

    public static Answer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Answer().mergeFrom(input);
    }
  }

  public static final class UserAnswer extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UserAnswer[] _emptyArray;
    public static UserAnswer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UserAnswer[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 uid = 1;
    private long uid_;
    public long getUid() {
      return uid_;
    }
    public UserAnswer setUid(long value) {
      uid_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public UserAnswer clearUid() {
      uid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 answerId = 2;
    private long answerId_;
    public long getAnswerId() {
      return answerId_;
    }
    public UserAnswer setAnswerId(long value) {
      answerId_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasAnswerId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public UserAnswer clearAnswerId() {
      answerId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public UserAnswer() {
      clear();
    }

    public UserAnswer clear() {
      bitField0_ = 0;
      uid_ = 0L;
      answerId_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, answerId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, answerId_);
      }
      return size;
    }

    @Override
    public UserAnswer mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            uid_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            answerId_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static UserAnswer parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UserAnswer(), data);
    }

    public static UserAnswer parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UserAnswer().mergeFrom(input);
    }
  }

  public static final class QuestionResult extends
      com.google.protobuf.nano.MessageNano {

    private static volatile QuestionResult[] _emptyArray;
    public static QuestionResult[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new QuestionResult[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 questionId = 1;
    private long questionId_;
    public long getQuestionId() {
      return questionId_;
    }
    public QuestionResult setQuestionId(long value) {
      questionId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasQuestionId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public QuestionResult clearQuestionId() {
      questionId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // repeated .wh.svc.tacit.UserAnswer userAnswers = 2;
    public com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer[] userAnswers;

    // optional int64 showMs = 3;
    private long showMs_;
    public long getShowMs() {
      return showMs_;
    }
    public QuestionResult setShowMs(long value) {
      showMs_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasShowMs() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public QuestionResult clearShowMs() {
      showMs_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int32 questionOrder = 4;
    private int questionOrder_;
    public int getQuestionOrder() {
      return questionOrder_;
    }
    public QuestionResult setQuestionOrder(int value) {
      questionOrder_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasQuestionOrder() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public QuestionResult clearQuestionOrder() {
      questionOrder_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public QuestionResult() {
      clear();
    }

    public QuestionResult clear() {
      bitField0_ = 0;
      questionId_ = 0L;
      userAnswers = com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer.emptyArray();
      showMs_ = 0L;
      questionOrder_ = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, questionId_);
      }
      if (this.userAnswers != null && this.userAnswers.length > 0) {
        for (int i = 0; i < this.userAnswers.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer element = this.userAnswers[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(3, showMs_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, questionOrder_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, questionId_);
      }
      if (this.userAnswers != null && this.userAnswers.length > 0) {
        for (int i = 0; i < this.userAnswers.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer element = this.userAnswers[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, showMs_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, questionOrder_);
      }
      return size;
    }

    @Override
    public QuestionResult mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            questionId_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.userAnswers == null ? 0 : this.userAnswers.length;
            com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.userAnswers, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcTacit.UserAnswer();
            input.readMessage(newArray[i]);
            this.userAnswers = newArray;
            break;
          }
          case 24: {
            showMs_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
          case 32: {
            questionOrder_ = input.readInt32();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static QuestionResult parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new QuestionResult(), data);
    }

    public static QuestionResult parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new QuestionResult().mergeFrom(input);
    }
  }

  public static final class StartTacitNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile StartTacitNotifyInfo[] _emptyArray;
    public static StartTacitNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StartTacitNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string roundId = 1;
    private java.lang.String roundId_;
    @Nullable
    public java.lang.String getRoundId() {
      return roundId_;
    }
    public StartTacitNotifyInfo setRoundId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      roundId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public StartTacitNotifyInfo clearRoundId() {
      roundId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int32 questionCount = 2;
    private int questionCount_;
    public int getQuestionCount() {
      return questionCount_;
    }
    public StartTacitNotifyInfo setQuestionCount(int value) {
      questionCount_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasQuestionCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public StartTacitNotifyInfo clearQuestionCount() {
      questionCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional .wh.svc.tacit.Question question = 3;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcTacit.Question question;

    public StartTacitNotifyInfo() {
      clear();
    }

    public StartTacitNotifyInfo clear() {
      bitField0_ = 0;
      roundId_ = "";
      questionCount_ = 0;
      question = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, questionCount_);
      }
      if (this.question != null) {
        output.writeMessage(3, this.question);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, questionCount_);
      }
      if (this.question != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.question);
      }
      return size;
    }

    @Override
    public StartTacitNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            roundId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            questionCount_ = input.readInt32();
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            if (this.question == null) {
              this.question = new com.woohoo.app.common.protocol.nano.WhSvcTacit.Question();
            }
            input.readMessage(this.question);
            break;
          }
        }
      }
    }

    public static StartTacitNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new StartTacitNotifyInfo(), data);
    }

    public static StartTacitNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StartTacitNotifyInfo().mergeFrom(input);
    }
  }

  public static final class NextQuestionNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile NextQuestionNotifyInfo[] _emptyArray;
    public static NextQuestionNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NextQuestionNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string roundId = 1;
    private java.lang.String roundId_;
    @Nullable
    public java.lang.String getRoundId() {
      return roundId_;
    }
    public NextQuestionNotifyInfo setRoundId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      roundId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public NextQuestionNotifyInfo clearRoundId() {
      roundId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.tacit.QuestionResult preQuestionResult = 2;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcTacit.QuestionResult preQuestionResult;

    // optional .wh.svc.tacit.Question nextQuestion = 3;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcTacit.Question nextQuestion;

    public NextQuestionNotifyInfo() {
      clear();
    }

    public NextQuestionNotifyInfo clear() {
      bitField0_ = 0;
      roundId_ = "";
      preQuestionResult = null;
      nextQuestion = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, roundId_);
      }
      if (this.preQuestionResult != null) {
        output.writeMessage(2, this.preQuestionResult);
      }
      if (this.nextQuestion != null) {
        output.writeMessage(3, this.nextQuestion);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, roundId_);
      }
      if (this.preQuestionResult != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.preQuestionResult);
      }
      if (this.nextQuestion != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.nextQuestion);
      }
      return size;
    }

    @Override
    public NextQuestionNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            roundId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            if (this.preQuestionResult == null) {
              this.preQuestionResult = new com.woohoo.app.common.protocol.nano.WhSvcTacit.QuestionResult();
            }
            input.readMessage(this.preQuestionResult);
            break;
          }
          case 26: {
            if (this.nextQuestion == null) {
              this.nextQuestion = new com.woohoo.app.common.protocol.nano.WhSvcTacit.Question();
            }
            input.readMessage(this.nextQuestion);
            break;
          }
        }
      }
    }

    public static NextQuestionNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new NextQuestionNotifyInfo(), data);
    }

    public static NextQuestionNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NextQuestionNotifyInfo().mergeFrom(input);
    }
  }

  public static final class UserAnswerNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile UserAnswerNotifyInfo[] _emptyArray;
    public static UserAnswerNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new UserAnswerNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string roundId = 1;
    private java.lang.String roundId_;
    @Nullable
    public java.lang.String getRoundId() {
      return roundId_;
    }
    public UserAnswerNotifyInfo setRoundId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      roundId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public UserAnswerNotifyInfo clearRoundId() {
      roundId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 questionId = 2;
    private long questionId_;
    public long getQuestionId() {
      return questionId_;
    }
    public UserAnswerNotifyInfo setQuestionId(long value) {
      questionId_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasQuestionId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public UserAnswerNotifyInfo clearQuestionId() {
      questionId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int64 uid = 3;
    private long uid_;
    public long getUid() {
      return uid_;
    }
    public UserAnswerNotifyInfo setUid(long value) {
      uid_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasUid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public UserAnswerNotifyInfo clearUid() {
      uid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public UserAnswerNotifyInfo() {
      clear();
    }

    public UserAnswerNotifyInfo clear() {
      bitField0_ = 0;
      roundId_ = "";
      questionId_ = 0L;
      uid_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, questionId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, uid_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, questionId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, uid_);
      }
      return size;
    }

    @Override
    public UserAnswerNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            roundId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            questionId_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            uid_ = input.readInt64();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static UserAnswerNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new UserAnswerNotifyInfo(), data);
    }

    public static UserAnswerNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new UserAnswerNotifyInfo().mergeFrom(input);
    }
  }

  public static final class FinishTacitNotifyInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile FinishTacitNotifyInfo[] _emptyArray;
    public static FinishTacitNotifyInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new FinishTacitNotifyInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string roundId = 1;
    private java.lang.String roundId_;
    @Nullable
    public java.lang.String getRoundId() {
      return roundId_;
    }
    public FinishTacitNotifyInfo setRoundId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      roundId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoundId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public FinishTacitNotifyInfo clearRoundId() {
      roundId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 matchDegree = 2;
    private long matchDegree_;
    public long getMatchDegree() {
      return matchDegree_;
    }
    public FinishTacitNotifyInfo setMatchDegree(long value) {
      matchDegree_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasMatchDegree() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public FinishTacitNotifyInfo clearMatchDegree() {
      matchDegree_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional string title = 3;
    private java.lang.String title_;
    @Nullable
    public java.lang.String getTitle() {
      return title_;
    }
    public FinishTacitNotifyInfo setTitle(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      title_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public FinishTacitNotifyInfo clearTitle() {
      title_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public FinishTacitNotifyInfo() {
      clear();
    }

    public FinishTacitNotifyInfo clear() {
      bitField0_ = 0;
      roundId_ = "";
      matchDegree_ = 0L;
      title_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, matchDegree_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeString(3, title_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, roundId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, matchDegree_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, title_);
      }
      return size;
    }

    @Override
    public FinishTacitNotifyInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            roundId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            matchDegree_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            title_ = input.readString();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static FinishTacitNotifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new FinishTacitNotifyInfo(), data);
    }

    public static FinishTacitNotifyInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new FinishTacitNotifyInfo().mergeFrom(input);
    }
  }
}
