// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcCommon {

  // enum App
  public interface App {
    public static final int AppUnknown = 0;
    public static final int WooHoo = 1;
  }

  // enum Platform
  public interface Platform {
    public static final int PlatformUnknown = 0;
    public static final int PlatformAndroid = 1;
    public static final int PlatformIos = 2;
  }

  // enum ResponseCode
  public interface ResponseCode {
    public static final int Success = 0;
    public static final int ErrSystem = 1;
    public static final int ErrUnauthorized = 2;
    public static final int ErrInvalidParameter = 3;
    public static final int ErrServerBusy = 4;
    public static final int ErrTooFrequency = 5;
    public static final int ErrRestricted = 6;
    public static final int ErrMaintenance = 7;
    public static final int ErrLowVersion = 8;
    public static final int ErrCensorWords = 9;
    public static final int ErrNotExists = 10;
    public static final int ErrExists = 11;
    public static final int ErrExceedLimit = 12;
    public static final int ErrUserFrozen = 1000;
    public static final int ErrRelationGreetSendMax = 1100;
    public static final int ErrRelationGreetToOneMax = 1101;
    public static final int ErrPartyRoomLimitedByKicked = 1200;
  }

  // enum Sex
  public interface Sex {
    public static final int SexUnknown = 0;
    public static final int FeMale = 1;
    public static final int Male = 2;
  }

  // enum UserAccountType
  public interface UserAccountType {
    public static final int AccountUnknown = 0;
    public static final int AccountFaceBook = 1;
    public static final int AccountGoogle = 2;
    public static final int AccountPhone = 3;
  }

  // enum RoomType
  public interface RoomType {
    public static final int RoomTypeUnknown = 0;
    public static final int VideoChat = 1;
    public static final int PartyRoom = 2;
  }

  public static final class ResponseHeader extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ResponseHeader[] _emptyArray;
    public static ResponseHeader[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ResponseHeader[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int32 resCode = 1;
    private int resCode_;
    public int getResCode() {
      return resCode_;
    }
    public ResponseHeader setResCode(int value) {
      resCode_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasResCode() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public ResponseHeader clearResCode() {
      resCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional string resMsg = 2;
    private java.lang.String resMsg_;
    @Nullable
    public java.lang.String getResMsg() {
      return resMsg_;
    }
    public ResponseHeader setResMsg(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      resMsg_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasResMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public ResponseHeader clearResMsg() {
      resMsg_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional string resTips = 3;
    private java.lang.String resTips_;
    @Nullable
    public java.lang.String getResTips() {
      return resTips_;
    }
    public ResponseHeader setResTips(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      resTips_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasResTips() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public ResponseHeader clearResTips() {
      resTips_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public ResponseHeader() {
      clear();
    }

    public ResponseHeader clear() {
      bitField0_ = 0;
      resCode_ = 0;
      resMsg_ = "";
      resTips_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, resCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeString(2, resMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeString(3, resTips_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, resCode_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, resMsg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, resTips_);
      }
      return size;
    }

    @Override
    public ResponseHeader mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            resCode_ = input.readInt32();
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            resMsg_ = input.readString();
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            resTips_ = input.readString();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static ResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ResponseHeader(), data);
    }

    public static ResponseHeader parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ResponseHeader().mergeFrom(input);
    }
  }

  public static final class NotifyHeader extends
      com.google.protobuf.nano.MessageNano {

    private static volatile NotifyHeader[] _emptyArray;
    public static NotifyHeader[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NotifyHeader[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 seqId = 1;
    private long seqId_;
    public long getSeqId() {
      return seqId_;
    }
    public NotifyHeader setSeqId(long value) {
      seqId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public NotifyHeader clearSeqId() {
      seqId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public NotifyHeader() {
      clear();
    }

    public NotifyHeader clear() {
      bitField0_ = 0;
      seqId_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, seqId_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, seqId_);
      }
      return size;
    }

    @Override
    public NotifyHeader mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            seqId_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static NotifyHeader parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new NotifyHeader(), data);
    }

    public static NotifyHeader parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NotifyHeader().mergeFrom(input);
    }
  }

  public static final class Empty extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Empty[] _emptyArray;
    public static Empty[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Empty[0];
          }
        }
      }
      return _emptyArray;
    }

    public Empty() {
      clear();
    }

    public Empty clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public Empty mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static Empty parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Empty(), data);
    }

    public static Empty parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Empty().mergeFrom(input);
    }
  }

  public static final class RoomVid extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RoomVid[] _emptyArray;
    public static RoomVid[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RoomVid[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 owner = 1;
    private long owner_;
    public long getOwner() {
      return owner_;
    }
    public RoomVid setOwner(long value) {
      owner_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public RoomVid clearOwner() {
      owner_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int32 type = 2;
    private int type_;
    public int getType() {
      return type_;
    }
    public RoomVid setType(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public RoomVid clearType() {
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional string session = 3;
    private java.lang.String session_;
    @Nullable
    public java.lang.String getSession() {
      return session_;
    }
    public RoomVid setSession(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      session_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasSession() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public RoomVid clearSession() {
      session_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public RoomVid() {
      clear();
    }

    public RoomVid clear() {
      bitField0_ = 0;
      owner_ = 0L;
      type_ = 0;
      session_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, owner_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeString(3, session_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, owner_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, session_);
      }
      return size;
    }

    @Override
    public RoomVid mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            owner_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            type_ = input.readInt32();
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            session_ = input.readString();
            bitField0_ |= 0x00000004;
            break;
          }
        }
      }
    }

    public static RoomVid parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RoomVid(), data);
    }

    public static RoomVid parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RoomVid().mergeFrom(input);
    }
  }
}
