// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcLocation {

  public static final class GetReportConfigReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetReportConfigReq[] _emptyArray;
    public static GetReportConfigReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetReportConfigReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public GetReportConfigReq() {
      clear();
    }

    public GetReportConfigReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public GetReportConfigReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static GetReportConfigReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetReportConfigReq(), data);
    }

    public static GetReportConfigReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetReportConfigReq().mergeFrom(input);
    }
  }

  public static final class GetReportConfigRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetReportConfigRes[] _emptyArray;
    public static GetReportConfigRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetReportConfigRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional int64 interval = 2;
    private long interval_;
    public long getInterval() {
      return interval_;
    }
    public GetReportConfigRes setInterval(long value) {
      interval_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public GetReportConfigRes clearInterval() {
      interval_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public GetReportConfigRes() {
      clear();
    }

    public GetReportConfigRes clear() {
      bitField0_ = 0;
      header = null;
      interval_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(2, interval_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, interval_);
      }
      return size;
    }

    @Override
    public GetReportConfigRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 16: {
            interval_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static GetReportConfigRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetReportConfigRes(), data);
    }

    public static GetReportConfigRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetReportConfigRes().mergeFrom(input);
    }
  }

  public static final class ReportLocationReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReportLocationReq[] _emptyArray;
    public static ReportLocationReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReportLocationReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional double latitude = 1;
    private double latitude_;
    public double getLatitude() {
      return latitude_;
    }
    public ReportLocationReq setLatitude(double value) {
      latitude_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public ReportLocationReq clearLatitude() {
      latitude_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional double longitude = 2;
    private double longitude_;
    public double getLongitude() {
      return longitude_;
    }
    public ReportLocationReq setLongitude(double value) {
      longitude_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public ReportLocationReq clearLongitude() {
      longitude_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional string city = 3;
    private java.lang.String city_;
    @Nullable
    public java.lang.String getCity() {
      return city_;
    }
    public ReportLocationReq setCity(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      city_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasCity() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public ReportLocationReq clearCity() {
      city_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional string country = 4;
    private java.lang.String country_;
    @Nullable
    public java.lang.String getCountry() {
      return country_;
    }
    public ReportLocationReq setCountry(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      country_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasCountry() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public ReportLocationReq clearCountry() {
      country_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public ReportLocationReq() {
      clear();
    }

    public ReportLocationReq clear() {
      bitField0_ = 0;
      latitude_ = 0D;
      longitude_ = 0D;
      city_ = "";
      country_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeString(3, city_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeString(4, country_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, city_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, country_);
      }
      return size;
    }

    @Override
    public ReportLocationReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 9: {
            latitude_ = input.readDouble();
            bitField0_ |= 0x00000001;
            break;
          }
          case 17: {
            longitude_ = input.readDouble();
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            city_ = input.readString();
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            country_ = input.readString();
            bitField0_ |= 0x00000008;
            break;
          }
        }
      }
    }

    public static ReportLocationReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReportLocationReq(), data);
    }

    public static ReportLocationReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReportLocationReq().mergeFrom(input);
    }
  }

  public static final class ReportLocationRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReportLocationRes[] _emptyArray;
    public static ReportLocationRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReportLocationRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public ReportLocationRes() {
      clear();
    }

    public ReportLocationRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public ReportLocationRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static ReportLocationRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReportLocationRes(), data);
    }

    public static ReportLocationRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReportLocationRes().mergeFrom(input);
    }
  }

  public static final class SwitchLocationReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SwitchLocationReq[] _emptyArray;
    public static SwitchLocationReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SwitchLocationReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional bool disable = 1;
    private boolean disable_;
    public boolean getDisable() {
      return disable_;
    }
    public SwitchLocationReq setDisable(boolean value) {
      disable_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasDisable() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public SwitchLocationReq clearDisable() {
      disable_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public SwitchLocationReq() {
      clear();
    }

    public SwitchLocationReq clear() {
      bitField0_ = 0;
      disable_ = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, disable_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, disable_);
      }
      return size;
    }

    @Override
    public SwitchLocationReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            disable_ = input.readBool();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static SwitchLocationReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SwitchLocationReq(), data);
    }

    public static SwitchLocationReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SwitchLocationReq().mergeFrom(input);
    }
  }

  public static final class SwitchLocationRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile SwitchLocationRes[] _emptyArray;
    public static SwitchLocationRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SwitchLocationRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public SwitchLocationRes() {
      clear();
    }

    public SwitchLocationRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public SwitchLocationRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static SwitchLocationRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SwitchLocationRes(), data);
    }

    public static SwitchLocationRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SwitchLocationRes().mergeFrom(input);
    }
  }
}
