// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcReport {

  // enum BizType
  public interface BizType {
    public static final int BizTypeUnknown = 0;
    public static final int PersonalInfo = 1;
    public static final int VideoRoom = 2;
    public static final int ChatMatchRecord = 3;
    public static final int IM = 4;
  }

  // enum ViolationType
  public interface ViolationType {
    public static final int ViolationTypeUnknown = 0;
    public static final int Advertisement = 1;
    public static final int Salacity = 2;
    public static final int Harass = 3;
    public static final int Illegal = 4;
  }

  // enum IMChatContentType
  public interface IMChatContentType {
    public static final int ContentTypeUnknown = 0;
    public static final int TEXT = 1;
    public static final int IMG = 2;
  }

  public static final class ReportViolationReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReportViolationReq[] _emptyArray;
    public static ReportViolationReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReportViolationReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.report.BizType bizType = 1;
    private int bizType_;
    public int getBizType() {
      return bizType_;
    }
    public ReportViolationReq setBizType(int value) {
      bizType_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasBizType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public ReportViolationReq clearBizType() {
      bizType_ = com.woohoo.app.common.protocol.nano.WhSvcReport.BizType.BizTypeUnknown;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.report.ViolationType violationType = 2;
    private int violationType_;
    public int getViolationType() {
      return violationType_;
    }
    public ReportViolationReq setViolationType(int value) {
      violationType_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasViolationType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public ReportViolationReq clearViolationType() {
      violationType_ = com.woohoo.app.common.protocol.nano.WhSvcReport.ViolationType.ViolationTypeUnknown;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional int64 targetUid = 3;
    private long targetUid_;
    public long getTargetUid() {
      return targetUid_;
    }
    public ReportViolationReq setTargetUid(long value) {
      targetUid_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasTargetUid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public ReportViolationReq clearTargetUid() {
      targetUid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional string desc = 4;
    private java.lang.String desc_;
    @Nullable
    public java.lang.String getDesc() {
      return desc_;
    }
    public ReportViolationReq setDesc(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      desc_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public ReportViolationReq clearDesc() {
      desc_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    // repeated string picList = 5;
    public java.lang.String[] picList;

    // optional int64 roomId = 6;
    private long roomId_;
    public long getRoomId() {
      return roomId_;
    }
    public ReportViolationReq setRoomId(long value) {
      roomId_ = value;
      bitField0_ |= 0x00000010;
      return this;
    }
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    public ReportViolationReq clearRoomId() {
      roomId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    // optional string chatId = 7;
    private java.lang.String chatId_;
    @Nullable
    public java.lang.String getChatId() {
      return chatId_;
    }
    public ReportViolationReq setChatId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      chatId_ = value;
      bitField0_ |= 0x00000020;
      return this;
    }
    public boolean hasChatId() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    public ReportViolationReq clearChatId() {
      chatId_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    // repeated .wh.svc.report.IMChatMessage messageList = 8;
    public com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage[] messageList;

    public ReportViolationReq() {
      clear();
    }

    public ReportViolationReq clear() {
      bitField0_ = 0;
      bizType_ = com.woohoo.app.common.protocol.nano.WhSvcReport.BizType.BizTypeUnknown;
      violationType_ = com.woohoo.app.common.protocol.nano.WhSvcReport.ViolationType.ViolationTypeUnknown;
      targetUid_ = 0L;
      desc_ = "";
      picList = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      roomId_ = 0L;
      chatId_ = "";
      messageList = com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, bizType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, violationType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, targetUid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeString(4, desc_);
      }
      if (this.picList != null && this.picList.length > 0) {
        for (int i = 0; i < this.picList.length; i++) {
          java.lang.String element = this.picList[i];
          if (element != null) {
            output.writeString(5, element);
          }
        }
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(6, roomId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeString(7, chatId_);
      }
      if (this.messageList != null && this.messageList.length > 0) {
        for (int i = 0; i < this.messageList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage element = this.messageList[i];
          if (element != null) {
            output.writeMessage(8, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, bizType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, violationType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, targetUid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, desc_);
      }
      if (this.picList != null && this.picList.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.picList.length; i++) {
          java.lang.String element = this.picList[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(6, roomId_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, chatId_);
      }
      if (this.messageList != null && this.messageList.length > 0) {
        for (int i = 0; i < this.messageList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage element = this.messageList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(8, element);
          }
        }
      }
      return size;
    }

    @Override
    public ReportViolationReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcReport.BizType.BizTypeUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.BizType.PersonalInfo:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.BizType.VideoRoom:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.BizType.ChatMatchRecord:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.BizType.IM:
                bizType_ = value;
                bitField0_ |= 0x00000001;
                break;
            }
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcReport.ViolationType.ViolationTypeUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.ViolationType.Advertisement:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.ViolationType.Salacity:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.ViolationType.Harass:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.ViolationType.Illegal:
                violationType_ = value;
                bitField0_ |= 0x00000002;
                break;
            }
            break;
          }
          case 24: {
            targetUid_ = input.readInt64();
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            desc_ = input.readString();
            bitField0_ |= 0x00000008;
            break;
          }
          case 42: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.picList == null ? 0 : this.picList.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.picList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.picList = newArray;
            break;
          }
          case 48: {
            roomId_ = input.readInt64();
            bitField0_ |= 0x00000010;
            break;
          }
          case 58: {
            chatId_ = input.readString();
            bitField0_ |= 0x00000020;
            break;
          }
          case 66: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 66);
            int i = this.messageList == null ? 0 : this.messageList.length;
            com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.messageList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatMessage();
            input.readMessage(newArray[i]);
            this.messageList = newArray;
            break;
          }
        }
      }
    }

    public static ReportViolationReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReportViolationReq(), data);
    }

    public static ReportViolationReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReportViolationReq().mergeFrom(input);
    }
  }

  public static final class IMChatMessage extends
      com.google.protobuf.nano.MessageNano {

    private static volatile IMChatMessage[] _emptyArray;
    public static IMChatMessage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new IMChatMessage[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional bool selfSend = 1;
    private boolean selfSend_;
    public boolean getSelfSend() {
      return selfSend_;
    }
    public IMChatMessage setSelfSend(boolean value) {
      selfSend_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasSelfSend() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public IMChatMessage clearSelfSend() {
      selfSend_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.report.IMChatContentType contentType = 2;
    private int contentType_;
    public int getContentType() {
      return contentType_;
    }
    public IMChatMessage setContentType(int value) {
      contentType_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasContentType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public IMChatMessage clearContentType() {
      contentType_ = com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatContentType.ContentTypeUnknown;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional string content = 3;
    private java.lang.String content_;
    @Nullable
    public java.lang.String getContent() {
      return content_;
    }
    public IMChatMessage setContent(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      content_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public IMChatMessage clearContent() {
      content_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional int64 timestamp = 4;
    private long timestamp_;
    public long getTimestamp() {
      return timestamp_;
    }
    public IMChatMessage setTimestamp(long value) {
      timestamp_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public IMChatMessage clearTimestamp() {
      timestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public IMChatMessage() {
      clear();
    }

    public IMChatMessage clear() {
      bitField0_ = 0;
      selfSend_ = false;
      contentType_ = com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatContentType.ContentTypeUnknown;
      content_ = "";
      timestamp_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, selfSend_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, contentType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeString(3, content_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, timestamp_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, selfSend_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(2, contentType_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, content_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, timestamp_);
      }
      return size;
    }

    @Override
    public IMChatMessage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            selfSend_ = input.readBool();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatContentType.ContentTypeUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatContentType.TEXT:
              case com.woohoo.app.common.protocol.nano.WhSvcReport.IMChatContentType.IMG:
                contentType_ = value;
                bitField0_ |= 0x00000002;
                break;
            }
            break;
          }
          case 26: {
            content_ = input.readString();
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            timestamp_ = input.readInt64();
            bitField0_ |= 0x00000008;
            break;
          }
        }
      }
    }

    public static IMChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new IMChatMessage(), data);
    }

    public static IMChatMessage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new IMChatMessage().mergeFrom(input);
    }
  }

  public static final class ReportViolationRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReportViolationRes[] _emptyArray;
    public static ReportViolationRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReportViolationRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public ReportViolationRes() {
      clear();
    }

    public ReportViolationRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public ReportViolationRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static ReportViolationRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReportViolationRes(), data);
    }

    public static ReportViolationRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReportViolationRes().mergeFrom(input);
    }
  }
}
