// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcUserRecommend {

  public static final class GetRecommendUserReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetRecommendUserReq[] _emptyArray;
    public static GetRecommendUserReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetRecommendUserReq[0];
          }
        }
      }
      return _emptyArray;
    }

    public GetRecommendUserReq() {
      clear();
    }

    public GetRecommendUserReq clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public GetRecommendUserReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static GetRecommendUserReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetRecommendUserReq(), data);
    }

    public static GetRecommendUserReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetRecommendUserReq().mergeFrom(input);
    }
  }

  public static final class GetRecommendUserRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile GetRecommendUserRes[] _emptyArray;
    public static GetRecommendUserRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new GetRecommendUserRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // repeated .wh.svc.ussrremd.FaceBookRecommendUser faceBookList = 2;
    public com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser[] faceBookList;

    // repeated .wh.svc.ussrremd.NearByRecommendUser nearByList = 3;
    public com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser[] nearByList;

    public GetRecommendUserRes() {
      clear();
    }

    public GetRecommendUserRes clear() {
      header = null;
      faceBookList = com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser.emptyArray();
      nearByList = com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (this.faceBookList != null && this.faceBookList.length > 0) {
        for (int i = 0; i < this.faceBookList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser element = this.faceBookList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.nearByList != null && this.nearByList.length > 0) {
        for (int i = 0; i < this.nearByList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser element = this.nearByList[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (this.faceBookList != null && this.faceBookList.length > 0) {
        for (int i = 0; i < this.faceBookList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser element = this.faceBookList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.nearByList != null && this.nearByList.length > 0) {
        for (int i = 0; i < this.nearByList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser element = this.nearByList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      return size;
    }

    @Override
    public GetRecommendUserRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.faceBookList == null ? 0 : this.faceBookList.length;
            com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.faceBookList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.FaceBookRecommendUser();
            input.readMessage(newArray[i]);
            this.faceBookList = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.nearByList == null ? 0 : this.nearByList.length;
            com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.nearByList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.NearByRecommendUser();
            input.readMessage(newArray[i]);
            this.nearByList = newArray;
            break;
          }
        }
      }
    }

    public static GetRecommendUserRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new GetRecommendUserRes(), data);
    }

    public static GetRecommendUserRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new GetRecommendUserRes().mergeFrom(input);
    }
  }

  public static final class FaceBookRecommendUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile FaceBookRecommendUser[] _emptyArray;
    public static FaceBookRecommendUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new FaceBookRecommendUser[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 uid = 1;
    private long uid_;
    public long getUid() {
      return uid_;
    }
    public FaceBookRecommendUser setUid(long value) {
      uid_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public FaceBookRecommendUser clearUid() {
      uid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public FaceBookRecommendUser() {
      clear();
    }

    public FaceBookRecommendUser clear() {
      bitField0_ = 0;
      uid_ = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, uid_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, uid_);
      }
      return size;
    }

    @Override
    public FaceBookRecommendUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            uid_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static FaceBookRecommendUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new FaceBookRecommendUser(), data);
    }

    public static FaceBookRecommendUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new FaceBookRecommendUser().mergeFrom(input);
    }
  }

  public static final class NearByRecommendUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile NearByRecommendUser[] _emptyArray;
    public static NearByRecommendUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NearByRecommendUser[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 uid = 1;
    private long uid_;
    public long getUid() {
      return uid_;
    }
    public NearByRecommendUser setUid(long value) {
      uid_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public NearByRecommendUser clearUid() {
      uid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.ussrremd.RecommendUserLocation location = 2;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.RecommendUserLocation location;

    public NearByRecommendUser() {
      clear();
    }

    public NearByRecommendUser clear() {
      bitField0_ = 0;
      uid_ = 0L;
      location = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, uid_);
      }
      if (this.location != null) {
        output.writeMessage(2, this.location);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, uid_);
      }
      if (this.location != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.location);
      }
      return size;
    }

    @Override
    public NearByRecommendUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            uid_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            if (this.location == null) {
              this.location = new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.RecommendUserLocation();
            }
            input.readMessage(this.location);
            break;
          }
        }
      }
    }

    public static NearByRecommendUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new NearByRecommendUser(), data);
    }

    public static NearByRecommendUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NearByRecommendUser().mergeFrom(input);
    }
  }

  public static final class RecommendUserLocation extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RecommendUserLocation[] _emptyArray;
    public static RecommendUserLocation[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RecommendUserLocation[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional double distance = 2;
    private double distance_;
    public double getDistance() {
      return distance_;
    }
    public RecommendUserLocation setDistance(double value) {
      distance_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public RecommendUserLocation clearDistance() {
      distance_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional string city = 3;
    private java.lang.String city_;
    @Nullable
    public java.lang.String getCity() {
      return city_;
    }
    public RecommendUserLocation setCity(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      city_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasCity() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public RecommendUserLocation clearCity() {
      city_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public RecommendUserLocation() {
      clear();
    }

    public RecommendUserLocation clear() {
      bitField0_ = 0;
      distance_ = 0D;
      city_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(2, distance_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeString(3, city_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(2, distance_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, city_);
      }
      return size;
    }

    @Override
    public RecommendUserLocation mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 17: {
            distance_ = input.readDouble();
            bitField0_ |= 0x00000001;
            break;
          }
          case 26: {
            city_ = input.readString();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static RecommendUserLocation parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RecommendUserLocation(), data);
    }

    public static RecommendUserLocation parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RecommendUserLocation().mergeFrom(input);
    }
  }

  public static final class ReportThirdFriendReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReportThirdFriendReq[] _emptyArray;
    public static ReportThirdFriendReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReportThirdFriendReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.UserAccountType accountType = 1;
    private int accountType_;
    public int getAccountType() {
      return accountType_;
    }
    public ReportThirdFriendReq setAccountType(int value) {
      accountType_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasAccountType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public ReportThirdFriendReq clearAccountType() {
      accountType_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.UserAccountType.AccountUnknown;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // repeated .wh.svc.ussrremd.ThirdFriend thirdFriendList = 2;
    public com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend[] thirdFriendList;

    public ReportThirdFriendReq() {
      clear();
    }

    public ReportThirdFriendReq clear() {
      bitField0_ = 0;
      accountType_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.UserAccountType.AccountUnknown;
      thirdFriendList = com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, accountType_);
      }
      if (this.thirdFriendList != null && this.thirdFriendList.length > 0) {
        for (int i = 0; i < this.thirdFriendList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend element = this.thirdFriendList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, accountType_);
      }
      if (this.thirdFriendList != null && this.thirdFriendList.length > 0) {
        for (int i = 0; i < this.thirdFriendList.length; i++) {
          com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend element = this.thirdFriendList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }

    @Override
    public ReportThirdFriendReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.UserAccountType.AccountUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.UserAccountType.AccountFaceBook:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.UserAccountType.AccountGoogle:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.UserAccountType.AccountPhone:
                accountType_ = value;
                bitField0_ |= 0x00000001;
                break;
            }
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.thirdFriendList == null ? 0 : this.thirdFriendList.length;
            com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend[] newArray =
                new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.thirdFriendList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.woohoo.app.common.protocol.nano.WhSvcUserRecommend.ThirdFriend();
            input.readMessage(newArray[i]);
            this.thirdFriendList = newArray;
            break;
          }
        }
      }
    }

    public static ReportThirdFriendReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReportThirdFriendReq(), data);
    }

    public static ReportThirdFriendReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReportThirdFriendReq().mergeFrom(input);
    }
  }

  public static final class ReportThirdFriendRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ReportThirdFriendRes[] _emptyArray;
    public static ReportThirdFriendRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ReportThirdFriendRes[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    public ReportThirdFriendRes() {
      clear();
    }

    public ReportThirdFriendRes clear() {
      header = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      return size;
    }

    @Override
    public ReportThirdFriendRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
        }
      }
    }

    public static ReportThirdFriendRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ReportThirdFriendRes(), data);
    }

    public static ReportThirdFriendRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ReportThirdFriendRes().mergeFrom(input);
    }
  }

  public static final class ThirdFriend extends
      com.google.protobuf.nano.MessageNano {

    private static volatile ThirdFriend[] _emptyArray;
    public static ThirdFriend[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ThirdFriend[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional string openId = 1;
    private java.lang.String openId_;
    @Nullable
    public java.lang.String getOpenId() {
      return openId_;
    }
    public ThirdFriend setOpenId(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      openId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasOpenId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public ThirdFriend clearOpenId() {
      openId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional string nick = 2;
    private java.lang.String nick_;
    @Nullable
    public java.lang.String getNick() {
      return nick_;
    }
    public ThirdFriend setNick(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      nick_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasNick() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public ThirdFriend clearNick() {
      nick_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional string avatar = 3;
    private java.lang.String avatar_;
    @Nullable
    public java.lang.String getAvatar() {
      return avatar_;
    }
    public ThirdFriend setAvatar(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      avatar_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasAvatar() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public ThirdFriend clearAvatar() {
      avatar_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // optional .wh.svc.common.Sex sex = 4;
    private int sex_;
    public int getSex() {
      return sex_;
    }
    public ThirdFriend setSex(int value) {
      sex_ = value;
      bitField0_ |= 0x00000008;
      return this;
    }
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    public ThirdFriend clearSex() {
      sex_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    public ThirdFriend() {
      clear();
    }

    public ThirdFriend clear() {
      bitField0_ = 0;
      openId_ = "";
      nick_ = "";
      avatar_ = "";
      sex_ = com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(1, openId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeString(2, nick_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeString(3, avatar_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, sex_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, openId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, nick_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, avatar_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(4, sex_);
      }
      return size;
    }

    @Override
    public ThirdFriend mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            openId_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            nick_ = input.readString();
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            avatar_ = input.readString();
            bitField0_ |= 0x00000004;
            break;
          }
          case 32: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.SexUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.FeMale:
              case com.woohoo.app.common.protocol.nano.WhSvcCommon.Sex.Male:
                sex_ = value;
                bitField0_ |= 0x00000008;
                break;
            }
            break;
          }
        }
      }
    }

    public static ThirdFriend parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ThirdFriend(), data);
    }

    public static ThirdFriend parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ThirdFriend().mergeFrom(input);
    }
  }
}
