// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.woohoo.app.common.protocol.nano;

import org.jetbrains.annotations.Nullable;
@SuppressWarnings("hiding")
public interface WhSvcChatroom {

  // enum TokenType
  public interface TokenType {
    public static final int TokenUnknown = 0;
    public static final int TokenVideo = 1;
    public static final int TokenAudio = 2;
  }

  public static final class CreateMediaTokenReq extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CreateMediaTokenReq[] _emptyArray;
    public static CreateMediaTokenReq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CreateMediaTokenReq[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.RoomVid roomVid = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.RoomVid roomVid;

    // optional int64 roomId = 2;
    private long roomId_;
    public long getRoomId() {
      return roomId_;
    }
    public CreateMediaTokenReq setRoomId(long value) {
      roomId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CreateMediaTokenReq clearRoomId() {
      roomId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional .wh.svc.chatroom.TokenType type = 3;
    private int type_;
    public int getType() {
      return type_;
    }
    public CreateMediaTokenReq setType(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public CreateMediaTokenReq clearType() {
      type_ = com.woohoo.app.common.protocol.nano.WhSvcChatroom.TokenType.TokenUnknown;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public CreateMediaTokenReq() {
      clear();
    }

    public CreateMediaTokenReq clear() {
      bitField0_ = 0;
      roomVid = null;
      roomId_ = 0L;
      type_ = com.woohoo.app.common.protocol.nano.WhSvcChatroom.TokenType.TokenUnknown;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.roomVid != null) {
        output.writeMessage(1, this.roomVid);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(2, roomId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, type_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.roomVid != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.roomVid);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, roomId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, type_);
      }
      return size;
    }

    @Override
    public CreateMediaTokenReq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.roomVid == null) {
              this.roomVid = new com.woohoo.app.common.protocol.nano.WhSvcCommon.RoomVid();
            }
            input.readMessage(this.roomVid);
            break;
          }
          case 16: {
            roomId_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case com.woohoo.app.common.protocol.nano.WhSvcChatroom.TokenType.TokenUnknown:
              case com.woohoo.app.common.protocol.nano.WhSvcChatroom.TokenType.TokenVideo:
              case com.woohoo.app.common.protocol.nano.WhSvcChatroom.TokenType.TokenAudio:
                type_ = value;
                bitField0_ |= 0x00000002;
                break;
            }
            break;
          }
        }
      }
    }

    public static CreateMediaTokenReq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CreateMediaTokenReq(), data);
    }

    public static CreateMediaTokenReq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CreateMediaTokenReq().mergeFrom(input);
    }
  }

  public static final class CreateMediaTokenRes extends
      com.google.protobuf.nano.MessageNano {

    private static volatile CreateMediaTokenRes[] _emptyArray;
    public static CreateMediaTokenRes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new CreateMediaTokenRes[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional .wh.svc.common.ResponseHeader header = 1;
    @Nullable
    public com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader header;

    // optional string token = 2;
    private java.lang.String token_;
    @Nullable
    public java.lang.String getToken() {
      return token_;
    }
    public CreateMediaTokenRes setToken(java.lang.String value) {
      if (value == null) {
        throw new java.lang.NullPointerException();
      }
      token_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public CreateMediaTokenRes clearToken() {
      token_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public CreateMediaTokenRes() {
      clear();
    }

    public CreateMediaTokenRes clear() {
      bitField0_ = 0;
      header = null;
      token_ = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.header != null) {
        output.writeMessage(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeString(2, token_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.header != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.header);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, token_);
      }
      return size;
    }

    @Override
    public CreateMediaTokenRes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.header == null) {
              this.header = new com.woohoo.app.common.protocol.nano.WhSvcCommon.ResponseHeader();
            }
            input.readMessage(this.header);
            break;
          }
          case 18: {
            token_ = input.readString();
            bitField0_ |= 0x00000001;
            break;
          }
        }
      }
    }

    public static CreateMediaTokenRes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new CreateMediaTokenRes(), data);
    }

    public static CreateMediaTokenRes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new CreateMediaTokenRes().mergeFrom(input);
    }
  }

  public static final class PublicScreenMessageNotify extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PublicScreenMessageNotify[] _emptyArray;
    public static PublicScreenMessageNotify[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PublicScreenMessageNotify[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int64 roomId = 1;
    private long roomId_;
    public long getRoomId() {
      return roomId_;
    }
    public PublicScreenMessageNotify setRoomId(long value) {
      roomId_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public PublicScreenMessageNotify clearRoomId() {
      roomId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int64 sender = 2;
    private long sender_;
    public long getSender() {
      return sender_;
    }
    public PublicScreenMessageNotify setSender(long value) {
      sender_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasSender() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public PublicScreenMessageNotify clearSender() {
      sender_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    // optional bool system = 3;
    private boolean system_;
    public boolean getSystem() {
      return system_;
    }
    public PublicScreenMessageNotify setSystem(boolean value) {
      system_ = value;
      bitField0_ |= 0x00000004;
      return this;
    }
    public boolean hasSystem() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    public PublicScreenMessageNotify clearSystem() {
      system_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    // map<string, string> content = 4;
    public java.util.Map<java.lang.String, java.lang.String> content;

    public PublicScreenMessageNotify() {
      clear();
    }

    public PublicScreenMessageNotify clear() {
      bitField0_ = 0;
      roomId_ = 0L;
      sender_ = 0L;
      system_ = false;
      content = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, roomId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, sender_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, system_);
      }
      if (this.content != null) {
        com.google.protobuf.nano.InternalNano.serializeMapField(
          output, this.content, 4,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_STRING);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, roomId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, sender_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, system_);
      }
      if (this.content != null) {
        size += com.google.protobuf.nano.InternalNano.computeMapFieldSize(
          this.content, 4,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_STRING);
      }
      return size;
    }

    @Override
    public PublicScreenMessageNotify mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      com.google.protobuf.nano.MapFactories.MapFactory mapFactory =
        com.google.protobuf.nano.MapFactories.getMapFactory();
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            roomId_ = input.readInt64();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            sender_ = input.readInt64();
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            system_ = input.readBool();
            bitField0_ |= 0x00000004;
            break;
          }
          case 34: {
            this.content = com.google.protobuf.nano.InternalNano.mergeMapEntry(
              input, this.content, mapFactory,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              null,
              10, 18);

            break;
          }
        }
      }
    }

    public static PublicScreenMessageNotify parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PublicScreenMessageNotify(), data);
    }

    public static PublicScreenMessageNotify parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PublicScreenMessageNotify().mergeFrom(input);
    }
  }
}
